// Tutorial step definitions for interactive guided tours
// SISTEMA TUTORIAL INTERATTIVO COMPLETO
// - Cursor animato su OGNI step operativo
// - Spotlight evidenziazione elemento
// - Auto-avanzamento con tempi di lettura calibrati
// - Descrizioni operative dettagliate

export interface TutorialStep {
  id: string;
  title: string;
  description: string;
  targetSelector?: string;
  route?: string;
  position?: 'top' | 'bottom' | 'left' | 'right' | 'center';
  action?: 'click' | 'type' | 'scroll' | 'hover' | 'wait' | 'drag';
  actionDelay?: number; // ms prima di animare il cursore
  highlightPadding?: number;
  cursorOffset?: { x: number; y: number };
  readingTime?: number; // secondi di lettura (auto-calcolato se non specificato)
}

export interface Tutorial {
  id: string;
  title: string;
  description: string;
  icon: string;
  estimatedTime: string;
  category: 'principale' | 'commesse' | 'hse' | 'commerciale' | 'amministrazione' | 'logistica' | 'compliance';
  steps: TutorialStep[];
}

export const tutorials: Tutorial[] = [
  // ==================== PRINCIPALE ====================
  {
    id: 'dashboard-tour',
    title: 'Tour Dashboard Completo',
    description: 'Panoramica interattiva di tutti gli elementi della dashboard principale',
    icon: 'LayoutDashboard',
    estimatedTime: '5 min',
    category: 'principale',
    steps: [
      {
        id: 'intro',
        title: 'Benvenuto in Gest-e! 👋',
        description: 'Questo tour ti guiderà attraverso la Dashboard principale. Qui troverai una panoramica in tempo reale di: cantieri attivi, alert di sicurezza, scadenze critiche, task assegnate e molto altro. La Dashboard è il punto di partenza per ogni operazione quotidiana.',
        targetSelector: '[data-tutorial="main-content"]',
        position: 'center',
        route: '/dashboard',
        action: 'wait',
        highlightPadding: 50,
        readingTime: 8,
      },
      {
        id: 'stat-cards',
        title: '📊 Card Statistiche Rapide',
        description: 'Queste card mostrano i KPI principali in tempo reale: numero cantieri attivi, lavoratori operativi, alert sicurezza, task in scadenza. Ogni card è cliccabile per accedere ai dettagli. I colori indicano lo stato: verde=ok, giallo=attenzione, rosso=critico.',
        targetSelector: '[data-tutorial="stat-cards"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 7,
      },
      {
        id: 'sidebar-intro',
        title: '📂 Sidebar di Navigazione',
        description: 'Il menu laterale è organizzato per reparti aziendali: Principale, Commesse, HSE & Sicurezza, Ufficio Commerciale, Amministrazione, Logistica. Ogni sezione è espandibile per mostrare i moduli disponibili. Clicca sul nome della sezione per espanderla.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        action: 'click',
        highlightPadding: 10,
        readingTime: 7,
      },
      {
        id: 'search-global',
        title: '🔍 Ricerca Globale (Ctrl+K)',
        description: 'La ricerca globale ti permette di trovare qualsiasi elemento nel sistema: commesse, lavoratori, imprese, documenti, task. Premi Ctrl+K (o Cmd+K su Mac) per aprirla rapidamente da qualsiasi pagina. I risultati sono organizzati per categoria.',
        targetSelector: '[data-tutorial="global-search"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'notifications-center',
        title: '🔔 Centro Notifiche',
        description: 'Il centro notifiche raccoglie tutti gli avvisi importanti: documenti in scadenza, task assegnate, alert di sicurezza, promemoria. Le notifiche non lette sono evidenziate con un badge numerato. Clicca per vedere i dettagli e marcare come lette.',
        targetSelector: '[data-tutorial="notifications"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'critical-deadlines',
        title: '⚠️ Alert Scadenze Critiche',
        description: 'Questo pulsante mostra le scadenze critiche che richiedono attenzione immediata. Il badge rosso indica il numero di elementi scaduti o in scadenza imminente. Documenti scaduti possono causare blocco operativo del personale e sanzioni.',
        targetSelector: '[data-tutorial="critical-alerts"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'user-profile',
        title: '👤 Menu Utente e Impostazioni',
        description: 'Dal menu utente puoi accedere a: Profilo personale con le tue task, Impostazioni aziendali per configurare moduli e dati, Tema e personalizzazione UI, Logout. Le impostazioni permettono di configurare ogni aspetto del sistema.',
        targetSelector: '[data-tutorial="user-menu"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'theme-toggle',
        title: '🌓 Cambio Tema',
        description: 'Puoi passare tra tema chiaro e scuro con questo pulsante. Il tema si applica a tutta l\'applicazione. Nelle impostazioni trovi anche la personalizzazione avanzata: 15 colori, glassmorphism, animazioni e stile pulsanti.',
        targetSelector: '[data-tutorial="theme-toggle"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'complete',
        title: 'Dashboard Completata! ✨',
        description: 'Ora conosci tutti gli elementi della Dashboard. Da qui puoi monitorare l\'andamento di tutta l\'azienda in tempo reale. Prosegui con gli altri tutorial per imparare a usare ogni modulo specifico!',
        targetSelector: '[data-tutorial="main-content"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 50,
        readingTime: 6,
      },
    ],
  },
  {
    id: 'projects-management',
    title: 'Gestione Progetti e Task',
    description: 'Board Kanban, Tabella, Timeline Gantt e Calendario interattivo',
    icon: 'FolderKanban',
    estimatedTime: '6 min',
    category: 'principale',
    steps: [
      {
        id: 'intro',
        title: 'Modulo Gestione Progetti 📋',
        description: 'Il modulo Progetti ti permette di gestire tutte le task aziendali con 4 viste sincronizzate: Board Kanban per drag&drop, Tabella Notion-style, Timeline Gantt per pianificazione, Calendario interattivo. Ogni modifica si sincronizza tra tutte le viste.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 8,
      },
      {
        id: 'nav-to-progetti',
        title: '👆 Clicca su "Progetti"',
        description: 'Nel menu laterale, sezione Principale, trovi la voce "Progetti". Clicca per accedere al modulo di gestione task. Da qui potrai creare, modificare e monitorare tutte le attività aziendali.',
        targetSelector: '[data-tutorial="nav-progetti"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'progetti-header',
        title: '📊 Intestazione Pagina Progetti',
        description: 'In alto trovi: statistiche (totale task, completate, bloccate), barra di ricerca, filtri per stato/priorità/assegnatario, pulsanti per cambiare vista (Kanban/Tabella/Gantt/Calendario), e pulsante per creare nuova task.',
        targetSelector: '[data-tutorial="page-header"]',
        route: '/progetti',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 7,
      },
      {
        id: 'view-selector',
        title: '👁️ Selettore Vista',
        description: 'Questi pulsanti cambiano la modalità di visualizzazione: KANBAN per drag&drop tra colonne, TABELLA per editing inline stile Notion, GANTT per timeline temporale, CALENDARIO per vista mensile. La vista si ricorda tra le sessioni.',
        targetSelector: '[data-tutorial="view-tabs"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 10,
        readingTime: 7,
      },
      {
        id: 'kanban-board',
        title: '📊 Board Kanban',
        description: 'Le colonne rappresentano gli stati: Da Fare → In Corso → In Revisione → Completato. Trascina le card da una colonna all\'altra per cambiare stato. Le card mostrano: titolo, priorità (badge colorato), scadenza, assegnatario. Clicca su una card per i dettagli.',
        targetSelector: '[data-tutorial="kanban-columns"]',
        position: 'top',
        action: 'drag',
        highlightPadding: 15,
        readingTime: 8,
      },
      {
        id: 'task-card',
        title: '🎯 Card Task',
        description: 'Ogni card mostra: icona priorità (🔴 alta, 🟡 media, 🟢 bassa), titolo, descrizione breve, scadenza, assegnatario. Il bordo sinistro indica la priorità. Clicca per aprire il dettaglio completo con note, allegati e storico.',
        targetSelector: '[data-tutorial="task-card"]',
        position: 'right',
        action: 'click',
        highlightPadding: 10,
        readingTime: 7,
      },
      {
        id: 'new-task-button',
        title: '➕ Crea Nuova Task',
        description: 'Clicca questo pulsante per creare una nuova task. Il form ti permette di specificare: titolo, descrizione, priorità, date inizio/fine, cantiere di riferimento, impresa, allegati. La task apparirà nella colonna "Da Fare".',
        targetSelector: '[data-tutorial="btn-new-task"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'filters',
        title: '🔍 Filtri e Ricerca',
        description: 'Usa i filtri per trovare rapidamente le task: per stato, priorità, assegnatario, cantiere, date. La ricerca funziona su titolo e descrizione. I filtri si combinano tra loro. Clicca "Reset" per rimuovere tutti i filtri.',
        targetSelector: '[data-tutorial="filters"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 10,
        readingTime: 6,
      },
      {
        id: 'export-button',
        title: '📥 Esporta Excel',
        description: 'Clicca per esportare tutte le task visibili in un file Excel. L\'export include: titolo, stato, priorità, date, assegnatario, cantiere. Utile per report e condivisione con chi non ha accesso al sistema.',
        targetSelector: '[data-tutorial="btn-export"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'complete',
        title: 'Gestione Progetti Completata! 🎉',
        description: 'Ora sai usare il modulo Progetti in tutte le sue viste. Prova a creare una task e a trascinarla tra le colonne del Kanban. Ricorda: le modifiche si sincronizzano automaticamente tra tutte le viste!',
        targetSelector: '[data-tutorial="kanban-columns"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 6,
      },
    ],
  },

  // ==================== COMMESSE ====================
  {
    id: 'create-commessa',
    title: 'Creare una Nuova Commessa',
    description: 'Processo completo di creazione commessa con tutti i dati richiesti',
    icon: 'Briefcase',
    estimatedTime: '7 min',
    category: 'commesse',
    steps: [
      {
        id: 'intro',
        title: 'Cos\'è una Commessa? 🏗️',
        description: 'La Commessa (o Cantiere) è l\'entità centrale del sistema. Rappresenta un progetto/opera con: anagrafica completa, dati economici (importo, SAL), figure responsabili (DL, CSP, CSE, RSPP), imprese subappaltatrici, lavoratori assegnati, documenti, e storico attività.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 9,
      },
      {
        id: 'nav-to-cantieri',
        title: '👆 Clicca su "Commesse"',
        description: 'Nel menu laterale, espandi la sezione "Commesse" e clicca sulla voce "Commesse". Questa è la pagina principale per gestire tutti i cantieri/progetti dell\'azienda.',
        targetSelector: '[data-tutorial="nav-cantieri"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'cantieri-list',
        title: '📋 Elenco Commesse',
        description: 'Ogni commessa è rappresentata da una card con: semaforo stato documenti (🟢🟡🔴), nome, codice commessa, committente, importo contratto, barra avanzamento SAL. Le card sono cliccabili per accedere ai dettagli.',
        targetSelector: '[data-tutorial="cantieri-list"]',
        route: '/cantieri',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 7,
      },
      {
        id: 'new-cantiere-button',
        title: '➕ Nuova Commessa',
        description: 'Clicca questo pulsante per aprire il form di creazione nuova commessa. Il form è organizzato in sezioni: Dati Generali, Ubicazione, Date, Importi, Figure Responsabili.',
        targetSelector: '[data-tutorial="btn-nuovo-cantiere"]',
        position: 'bottom',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'form-section-dati',
        title: '📝 Sezione Dati Generali',
        description: 'Compila: Nome Commessa (descrittivo e univoco), Codice Commessa (es. COM-2025-001), Committente (cliente), Tipo lavori. Il codice commessa deve essere univoco nel sistema.',
        targetSelector: '[data-tutorial="form-cantiere"]',
        position: 'left',
        action: 'hover',
        highlightPadding: 20,
        readingTime: 6,
      },
      {
        id: 'field-nome',
        title: '📌 Campo Nome Commessa',
        description: 'Inserisci un nome chiaro e descrittivo. Esempio: "Ristrutturazione Palazzo Rossi - Milano". Il nome apparirà in tutte le liste e nei documenti generati.',
        targetSelector: '[data-tutorial="field-nome"]',
        position: 'right',
        action: 'type',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'field-codice',
        title: '🔢 Campo Codice Commessa',
        description: 'Il codice deve essere univoco e seguire un formato aziendale. Formati consigliati: COM-2025-001, PRJ-MI-0001. Questo codice identifica la commessa in tutti i documenti e report.',
        targetSelector: '[data-tutorial="field-codice"]',
        position: 'right',
        action: 'type',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'field-importo',
        title: '💰 Campo Importo Contratto',
        description: 'Inserisci il valore economico totale del contratto in Euro. Questo importo serve per: calcolo percentuale SAL, fatturazione, analisi marginalità, report economici. IVA esclusa.',
        targetSelector: '[data-tutorial="field-importo"]',
        position: 'right',
        action: 'type',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'field-date',
        title: '📅 Date Inizio e Fine',
        description: 'Data Inizio: primo giorno operativo. Data Fine Prevista: termine contrattuale. Queste date alimentano: timeline Gantt, scadenziario, alert ritardi. La Data Fine Effettiva si compila a chiusura lavori.',
        targetSelector: '[data-tutorial="field-date"]',
        position: 'right',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'field-responsabili',
        title: '👷 Figure Responsabili',
        description: 'Compila le figure obbligatorie per D.Lgs 81/08: Direttore Lavori (DL), Coordinatore Sicurezza Progettazione (CSP), Coordinatore Sicurezza Esecuzione (CSE), Responsabile Sicurezza (RSPP). Queste figure appaiono nei documenti ufficiali.',
        targetSelector: '[data-tutorial="field-responsabile"]',
        position: 'right',
        action: 'click',
        highlightPadding: 8,
        readingTime: 7,
      },
      {
        id: 'save-button',
        title: '💾 Salva Commessa',
        description: 'Clicca "Salva" per creare la commessa. Il sistema verifica i campi obbligatori e la unicità del codice. Dopo il salvataggio, la commessa appare nell\'elenco e puoi procedere ad assegnare imprese e lavoratori.',
        targetSelector: '[data-tutorial="btn-salva-cantiere"]',
        position: 'top',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'complete',
        title: 'Creazione Commessa Completata! 🎉',
        description: 'Hai creato la tua prima commessa! Prossimi passi: 1) Assegna imprese subappaltatrici, 2) Assegna lavoratori, 3) Carica documenti (PSC, POS), 4) Registra i primi SAL. Ogni commessa ha il suo centro di controllo dedicato.',
        targetSelector: '[data-tutorial="cantieri-list"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 7,
      },
    ],
  },
  {
    id: 'commessa-detail',
    title: 'Gestione Dettaglio Commessa',
    description: 'Panoramica, imprese, lavoratori, documenti, SAL',
    icon: 'FileText',
    estimatedTime: '6 min',
    category: 'commesse',
    steps: [
      {
        id: 'intro',
        title: 'Centro di Controllo Commessa 📋',
        description: 'La pagina dettaglio commessa è il centro operativo di ogni progetto. Da qui gestisci tutto: panoramica generale, imprese subappaltatrici, lavoratori assegnati, documentazione, stati avanzamento lavori (SAL).',
        targetSelector: '[data-tutorial="cantieri-list"]',
        position: 'bottom',
        route: '/cantieri',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 7,
      },
      {
        id: 'select-commessa',
        title: '👆 Seleziona una Commessa',
        description: 'Clicca su una card commessa per accedere alla pagina di dettaglio. Il semaforo sulla card indica lo stato documenti: 🟢 tutti ok, 🟡 in scadenza, 🔴 scaduti o mancanti.',
        targetSelector: '[data-tutorial="cantiere-card"]',
        position: 'right',
        action: 'click',
        highlightPadding: 10,
        readingTime: 5,
      },
      {
        id: 'detail-header',
        title: '📊 Intestazione Dettaglio',
        description: 'L\'intestazione mostra: nome commessa, stato, committente, importo, date, barra avanzamento SAL percentuale. I pulsanti permettono di modificare i dati o generare documenti.',
        targetSelector: '[data-tutorial="detail-header"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 6,
      },
      {
        id: 'tabs-navigation',
        title: '📑 Navigazione Tab',
        description: 'I tab organizzano le informazioni: Panoramica (riepilogo), Imprese (subappaltatori), Lavoratori (personale), Documenti (PSC, POS, autorizzazioni), SAL (avanzamento economico). Clicca su un tab per cambiare sezione.',
        targetSelector: '[data-tutorial="detail-tabs"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 10,
        readingTime: 7,
      },
      {
        id: 'tab-imprese',
        title: '🏢 Tab Imprese',
        description: 'Qui gestisci le imprese subappaltatrici assegnate alla commessa. Per ogni impresa vedi: ragione sociale, tipologia, semaforo documenti, date contratto. Puoi aggiungere nuove imprese o rimuovere quelle esistenti.',
        targetSelector: '[data-tutorial="tab-imprese"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'tab-lavoratori',
        title: '👷 Tab Lavoratori',
        description: 'Qui gestisci il personale operante in cantiere. Per ogni lavoratore vedi: nome, impresa, mansione, semaforo formazioni/visite. Il semaforo rosso indica impossibilità di operare per documenti scaduti.',
        targetSelector: '[data-tutorial="tab-lavoratori"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'tab-documenti',
        title: '📄 Tab Documenti',
        description: 'Gestione documentale completa: PSC (Piano Sicurezza Coordinamento), POS (Piano Operativo Sicurezza) per impresa, autorizzazioni, permessi, certificati. Ogni documento ha: data emissione, scadenza, stato, file allegato.',
        targetSelector: '[data-tutorial="tab-documenti"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'tab-sal',
        title: '📈 Tab SAL',
        description: 'Stato Avanzamento Lavori: registra le percentuali di completamento e gli importi fatturati. Ogni SAL ha: numero progressivo, data, percentuale, importo, note. I SAL alimentano la barra avanzamento in intestazione.',
        targetSelector: '[data-tutorial="tab-sal"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'complete',
        title: 'Dettaglio Commessa Completato! ✨',
        description: 'Ora conosci tutte le sezioni del dettaglio commessa. Usa i tab per navigare tra le diverse aree. Ricorda: il semaforo in intestazione riflette lo stato complessivo di documenti e compliance.',
        targetSelector: '[data-tutorial="detail-header"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 6,
      },
    ],
  },

  // ==================== HSE & SICUREZZA ====================
  {
    id: 'manage-lavoratori',
    title: 'Gestione Anagrafica Lavoratori',
    description: 'Dati, formazioni, visite mediche, DPI, documenti',
    icon: 'Users',
    estimatedTime: '8 min',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Anagrafica Lavoratori 👷',
        description: 'Il modulo Lavoratori gestisce l\'anagrafica completa del personale: dati personali, impresa di appartenenza, mansione, formazioni obbligatorie (D.Lgs 81/08), visite mediche con giudizi idoneità, DPI assegnati, documenti personali. Il sistema monitora automaticamente le scadenze.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 9,
      },
      {
        id: 'nav-to-lavoratori',
        title: '👆 Clicca su "Lavoratori"',
        description: 'Nel menu laterale, sezione "Sicurezza & HSE", clicca sulla voce "Lavoratori". Questa è l\'anagrafica centrale per gestire tutto il personale aziendale e dei subappaltatori.',
        targetSelector: '[data-tutorial="nav-lavoratori"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'lavoratori-list',
        title: '📋 Elenco Lavoratori',
        description: 'La tabella mostra tutti i lavoratori con: semaforo stato (🟢🟡🔴), nome cognome, impresa, mansione, stato formazioni, prossima visita medica, cantieri assegnati. Il semaforo rosso indica NON IDONEITÀ al lavoro.',
        targetSelector: '[data-tutorial="lavoratori-list"]',
        route: '/lavoratori',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 7,
      },
      {
        id: 'traffic-light-system',
        title: '🚦 Sistema Semaforo Compliance',
        description: 'Il semaforo indica lo stato complessivo: 🟢 VERDE = tutto in regola, può lavorare. 🟡 GIALLO = elementi in scadenza entro 30gg, verificare. 🔴 ROSSO = elementi scaduti, NON può operare in cantiere. Lavoratore rosso = sanzioni D.Lgs 81/08.',
        targetSelector: '[data-tutorial="traffic-light"]',
        position: 'right',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 8,
      },
      {
        id: 'new-lavoratore-button',
        title: '➕ Nuovo Lavoratore',
        description: 'Clicca per aggiungere un nuovo lavoratore. Il form richiede: dati anagrafici, impresa di appartenenza, mansione, codice fiscale. Dopo la creazione, potrai aggiungere formazioni, visite e DPI.',
        targetSelector: '[data-tutorial="btn-nuovo-lavoratore"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'select-lavoratore',
        title: '👆 Seleziona un Lavoratore',
        description: 'Clicca sulla riga di un lavoratore per aprire la scheda dettaglio. Qui puoi vedere e gestire tutte le informazioni: anagrafica, formazioni, visite mediche, DPI, documenti, cantieri assegnati.',
        targetSelector: '[data-tutorial="lavoratore-row"]',
        position: 'right',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'tab-formazioni',
        title: '📚 Tab Formazioni',
        description: 'Gestione corsi obbligatori: Formazione Generale, Formazione Specifica (rischio basso/medio/alto), Primo Soccorso, Antincendio, Preposti, Ponteggi, etc. Per ogni corso: data, scadenza, ente formatore, attestato allegato.',
        targetSelector: '[data-tutorial="tab-formazioni"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 7,
      },
      {
        id: 'add-formazione',
        title: '➕ Aggiungi Formazione',
        description: 'Clicca per registrare un nuovo corso. Seleziona il tipo corso, inserisci data conseguimento e scadenza, carica l\'attestato PDF. Il sistema calcola automaticamente lo stato in base alla scadenza.',
        targetSelector: '[data-tutorial="btn-add-formazione"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'tab-visite',
        title: '🏥 Tab Visite Mediche',
        description: 'Storico visite mediche con giudizi di idoneità: Idoneo, Idoneo con prescrizioni, Idoneo con limitazioni, Temporaneamente non idoneo, Non idoneo. Il giudizio "Non idoneo" blocca l\'operatività del lavoratore.',
        targetSelector: '[data-tutorial="tab-visite"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 7,
      },
      {
        id: 'tab-dpi',
        title: '🦺 Tab DPI',
        description: 'Dispositivi di Protezione Individuale consegnati: casco, guanti, scarpe, imbracatura, etc. Per ogni DPI: tipo, taglia, data consegna, data scadenza, stato. I DPI scaduti contribuiscono al semaforo rosso.',
        targetSelector: '[data-tutorial="tab-dpi"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'complete',
        title: 'Gestione Lavoratori Completata! 🎉',
        description: 'Ora sai gestire l\'anagrafica completa dei lavoratori. Ricorda: monitora sempre il semaforo! Un lavoratore con semaforo rosso NON può operare in cantiere. Le sanzioni per non conformità D.Lgs 81/08 sono severe.',
        targetSelector: '[data-tutorial="lavoratori-list"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 7,
      },
    ],
  },
  {
    id: 'manage-imprese',
    title: 'Gestione Imprese Subappaltatrici',
    description: 'Anagrafica, documenti obbligatori, rating, assegnazioni',
    icon: 'Building2',
    estimatedTime: '6 min',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Anagrafica Imprese 🏢',
        description: 'Il modulo Imprese gestisce tutte le aziende subappaltatrici: dati societari, documenti obbligatori (DURC, Visura, DVR, Polizze), rating qualità, cantieri assegnati, lavoratori. Il sistema monitora la compliance documentale.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 8,
      },
      {
        id: 'nav-to-imprese',
        title: '👆 Clicca su "Imprese"',
        description: 'Nel menu laterale, sezione "Sicurezza & HSE", clicca sulla voce "Imprese". Qui gestisci tutte le aziende che operano nei tuoi cantieri come subappaltatori.',
        targetSelector: '[data-tutorial="nav-imprese"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 4,
      },
      {
        id: 'imprese-list',
        title: '📋 Elenco Imprese',
        description: 'La tabella mostra: semaforo documenti, ragione sociale, P.IVA, tipologia (subappaltatore, fornitore, etc.), referente, cantieri assegnati, conteggio documenti (ok/scadenza/scaduti).',
        targetSelector: '[data-tutorial="imprese-list"]',
        route: '/imprese',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 6,
      },
      {
        id: 'filter-imprese',
        title: '🔍 Filtri Imprese',
        description: 'Filtra per: tipologia (subappaltatore, fornitore, consulente), stato documenti (tutti ok, in scadenza, scaduti). La ricerca funziona su ragione sociale, P.IVA, referente. Usa i filtri per trovare imprese problematiche.',
        targetSelector: '[data-tutorial="filters"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 10,
        readingTime: 6,
      },
      {
        id: 'new-impresa-button',
        title: '➕ Nuova Impresa',
        description: 'Clicca per registrare una nuova impresa. Il form richiede: ragione sociale, P.IVA, codice fiscale, tipologia, dati contatto referente, email, PEC. Dopo la creazione, aggiungi i documenti obbligatori.',
        targetSelector: '[data-tutorial="btn-nuova-impresa"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'select-impresa',
        title: '👆 Seleziona un\'Impresa',
        description: 'Clicca sulla riga di un\'impresa per aprire la scheda dettaglio. Qui gestisci: dati societari, documenti con scadenze, lavoratori dipendenti, cantieri assegnati.',
        targetSelector: '[data-tutorial="impresa-row"]',
        position: 'right',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'tab-documenti-impresa',
        title: '📄 Tab Documenti Impresa',
        description: 'Documenti obbligatori per operare: DURC (validità 120gg), Visura Camerale, DVR, Polizza RCT/RCO, Certificazione SOA, etc. Per ogni documento: data emissione, scadenza, stato, file allegato. Il semaforo dipende da questi documenti.',
        targetSelector: '[data-tutorial="tab-documenti"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 7,
      },
      {
        id: 'add-documento-impresa',
        title: '➕ Aggiungi Documento',
        description: 'Clicca per caricare un nuovo documento. Seleziona tipo, inserisci numero, data emissione e scadenza, carica il file PDF. Il sistema calcola automaticamente lo stato e invia alert prima della scadenza.',
        targetSelector: '[data-tutorial="btn-add-documento"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'complete',
        title: 'Gestione Imprese Completata! 🎉',
        description: 'Ora sai gestire le imprese subappaltatrici. Ricorda: un\'impresa con documenti scaduti (DURC, DVR) NON può operare nei tuoi cantieri. Monitora regolarmente il semaforo per evitare blocchi operativi e sanzioni.',
        targetSelector: '[data-tutorial="imprese-list"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 7,
      },
    ],
  },
  {
    id: 'safety-dlgs81',
    title: 'Sicurezza D.Lgs 81/08',
    description: 'POS, DUVRI, Infortuni, Figure Sicurezza, Visite Mediche',
    icon: 'ShieldCheck',
    estimatedTime: '8 min',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Modulo Sicurezza D.Lgs 81/08 🛡️',
        description: 'Questo modulo implementa tutti gli adempimenti del Testo Unico Sicurezza: POS (Piano Operativo Sicurezza), DUVRI (Documento Unico Valutazione Rischi Interferenze), Registro Infortuni, Figure Sicurezza (RSPP, RLS, MC), Sorveglianza Sanitaria, Moduli Compilabili, Inventario DPI.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 10,
      },
      {
        id: 'nav-to-safety',
        title: '👆 Clicca su "Sicurezza D.Lgs 81/08"',
        description: 'Nel menu laterale, sezione "Sicurezza & HSE", clicca sulla voce "Sicurezza D.Lgs 81/08". Questo è il modulo centrale per la gestione della sicurezza secondo la normativa italiana.',
        targetSelector: '[data-tutorial="nav-sicurezza"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'safety-overview',
        title: '📊 Panoramica Sicurezza',
        description: 'La pagina mostra statistiche: POS attivi/scaduti, DUVRI, infortuni registrati, figure sicurezza con corsi, visite mediche. I tab organizzano le diverse sezioni. Il semaforo indica la compliance complessiva.',
        targetSelector: '[data-tutorial="safety-stats"]',
        route: '/sicurezza-dlgs81',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 7,
      },
      {
        id: 'tab-pos',
        title: '📋 Tab POS (Piano Operativo Sicurezza)',
        description: 'Gestione POS per ogni impresa/cantiere. Il POS è obbligatorio e deve contenere: analisi rischi, misure prevenzione, DPI richiesti, procedure emergenza. Puoi creare POS digitali con il form guidato.',
        targetSelector: '[data-tutorial="tab-pos"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 7,
      },
      {
        id: 'create-pos-digital',
        title: '➕ Crea POS Digitale',
        description: 'Il form guidato a 3 step: 1) Dati generali (cantiere, impresa, date), 2) Analisi rischi (rischi generici e specifici), 3) Misure prevenzione e DPI. Genera un documento professionale modificabile con editor.',
        targetSelector: '[data-tutorial="btn-new-pos"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 7,
      },
      {
        id: 'tab-infortuni',
        title: '🚑 Tab Registro Infortuni',
        description: 'Registro obbligatorio di tutti gli infortuni: data, lavoratore, cantiere, descrizione, giorni assenza, denuncia INAIL. Il registro digitale sostituisce quello cartaceo. Esportabile per ispezioni.',
        targetSelector: '[data-tutorial="tab-infortuni"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'tab-figure-sicurezza',
        title: '👤 Tab Figure Sicurezza (RSPP/RLS)',
        description: 'Gestione nomine: RSPP (Responsabile Servizio Prevenzione Protezione), RLS (Rappresentante Lavoratori Sicurezza), Medico Competente, Addetti Emergenze. Per ogni figura: nomina, corsi obbligatori con scadenze.',
        targetSelector: '[data-tutorial="tab-figure"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 7,
      },
      {
        id: 'tab-moduli',
        title: '📝 Tab Moduli Compilabili',
        description: 'Moduli standard D.Lgs 81/08 precompilati: Presa Visione PSC/POS, Nomina RSPP, Nomina RLS, Consegna DPI, Verbale Riunione Periodica. Compila, salva e scarica PDF con carta intestata aziendale.',
        targetSelector: '[data-tutorial="tab-moduli"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'tab-inventario-dpi',
        title: '🦺 Tab Inventario DPI',
        description: 'Magazzino DPI aziendali: caschi, guanti, scarpe, imbracature, etc. Per ogni DPI: quantità disponibile, soglia minima, alert sottoscorta. Gestione assegnazioni ai lavoratori con verbale consegna.',
        targetSelector: '[data-tutorial="tab-inventario"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'complete',
        title: 'Sicurezza D.Lgs 81/08 Completata! 🎉',
        description: 'Ora conosci tutti gli strumenti per la gestione della sicurezza. Ricorda: la documentazione sicurezza è soggetta a sanzioni penali in caso di non conformità. Usa il sistema per mantenere tutto aggiornato e tracciabile.',
        targetSelector: '[data-tutorial="safety-stats"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 7,
      },
    ],
  },

  // ==================== UFFICIO COMMERCIALE ====================
  {
    id: 'ufficio-commerciale',
    title: 'Ufficio Commerciale Completo',
    description: 'Fornitori, Contratti, Preventivi, Ordini, Listini',
    icon: 'Store',
    estimatedTime: '7 min',
    category: 'commerciale',
    steps: [
      {
        id: 'intro',
        title: 'Ufficio Commerciale 💼',
        description: 'Il modulo Ufficio Commerciale gestisce: Fornitori con documenti e rating, Contratti attivi e passivi, Preventivi, Ordini di acquisto, Listini prezzi. È il centro per tutte le operazioni commerciali e di approvvigionamento.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 8,
      },
      {
        id: 'nav-to-commerciale',
        title: '👆 Clicca su "Ufficio Commerciale"',
        description: 'Nel menu laterale, espandi la sezione "Ufficio Commerciale". Troverai: Fornitori, Contratti, Preventivi, Ordini, Listino Prezzi. Ogni modulo è dedicato a un\'area specifica.',
        targetSelector: '[data-tutorial="nav-commerciale"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'fornitori-overview',
        title: '🏭 Gestione Fornitori',
        description: 'Anagrafica fornitori con: dati societari, contatti, condizioni pagamento, rating qualità, documenti (DURC, Visura), stato "Pagabile" o "Blocco Pagamento" in base alla compliance documentale.',
        targetSelector: '[data-tutorial="nav-fornitori"]',
        route: '/ufficio-commerciale',
        position: 'right',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'contratti-tab',
        title: '📋 Gestione Contratti',
        description: 'Contratti attivi e passivi: cliente/fornitore, importo, date validità, clausole, allegati. Sistema di alert per scadenze e rinnovi automatici. Presa visione digitale tracciabile.',
        targetSelector: '[data-tutorial="tab-contratti"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'preventivi-tab',
        title: '📝 Preventivi',
        description: 'Creazione preventivi professionali: selezione voci da listino, quantità, sconti, note. Generazione PDF su carta intestata. Tracciamento stato: bozza, inviato, accettato, rifiutato.',
        targetSelector: '[data-tutorial="tab-preventivi"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'ordini-tab',
        title: '📦 Ordini Acquisto',
        description: 'Gestione ordini a fornitori: selezione fornitore, voci, quantità, prezzi concordati. Workflow: bozza → inviato → confermato → ricevuto. Collegamento a DDT e fatture.',
        targetSelector: '[data-tutorial="tab-ordini"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'listino-tab',
        title: '💰 Listino Prezzi',
        description: 'Database prezzi materiali e servizi: codice articolo, descrizione, unità misura, prezzo listino, sconto, prezzo netto, fornitore. Importazione da Excel, filtri per categoria.',
        targetSelector: '[data-tutorial="tab-listino"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'complete',
        title: 'Ufficio Commerciale Completato! 🎉',
        description: 'Ora conosci tutti i moduli dell\'Ufficio Commerciale. Usa il sistema per gestire l\'intero ciclo commerciale: dalla richiesta preventivo alla fatturazione, passando per ordini e contratti.',
        targetSelector: '[data-tutorial="main-content"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 6,
      },
    ],
  },

  // ==================== AMMINISTRAZIONE ====================
  {
    id: 'amministrazione',
    title: 'Reparto Amministrazione',
    description: 'Fatture, Note Spesa, Richieste Dipendenti, Organigramma',
    icon: 'Calculator',
    estimatedTime: '6 min',
    category: 'amministrazione',
    steps: [
      {
        id: 'intro',
        title: 'Reparto Amministrazione 📊',
        description: 'Il modulo Amministrazione gestisce: Fatture attive/passive con scadenziario, Note Spesa con workflow approvazione, Richieste Dipendenti (ferie, permessi, trasferte), DDT, Organigramma aziendale interattivo.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 8,
      },
      {
        id: 'nav-to-admin',
        title: '👆 Clicca su "Reparto Amministrazione"',
        description: 'Nel menu laterale, sezione "Amministrazione", clicca sulla voce "Reparto Amministrazione". Qui trovi tutti gli strumenti per la gestione amministrativa e finanziaria.',
        targetSelector: '[data-tutorial="nav-amministrazione"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 4,
      },
      {
        id: 'fatture-tab',
        title: '📄 Tab Fatture',
        description: 'Gestione fatture attive (emesse) e passive (ricevute): numero, data, cliente/fornitore, imponibile, IVA, totale, scadenza, stato pagamento. Blacklist automatica per ritardi. Export contabilità.',
        targetSelector: '[data-tutorial="tab-fatture"]',
        route: '/reparto-amministrazione',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 7,
      },
      {
        id: 'blacklist-tab',
        title: '⚠️ Tab Blacklist',
        description: 'Fatture scadute organizzate per urgenza: rosso (>30gg), arancione (15-30gg), giallo (1-14gg). Azioni rapide: sollecito, piano rientro, blocco forniture. Fondamentale per gestione crediti.',
        targetSelector: '[data-tutorial="tab-blacklist"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'note-spesa-tab',
        title: '🧾 Tab Note Spesa',
        description: 'Dipendenti inseriscono spese con: data, categoria, importo, allegato scontrino/ricevuta. Workflow approvazione: inserita → in approvazione → approvata/rifiutata → rimborsata. Report mensili.',
        targetSelector: '[data-tutorial="tab-notespesa"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'richieste-tab',
        title: '📋 Tab Richieste Dipendenti',
        description: 'Gestione ferie, permessi, trasferte, malattie. Calendario visivo con sovrapposizioni. Board Kanban per stato approvazione. Saldi ferie/permessi per dipendente. Notifiche automatiche.',
        targetSelector: '[data-tutorial="tab-richieste"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'organigramma-tab',
        title: '🏢 Tab Organigramma',
        description: 'Struttura gerarchica aziendale visiva: Direzione → Responsabili → Operativi. Aggiungi nodi, definisci riporti, gestisci ruoli. L\'organigramma appare anche nei documenti ufficiali.',
        targetSelector: '[data-tutorial="tab-organigramma"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'complete',
        title: 'Amministrazione Completata! 🎉',
        description: 'Ora conosci tutti i moduli amministrativi. Usa il sistema per: monitorare i crediti con la blacklist, approvare note spesa e richieste, mantenere aggiornato l\'organigramma.',
        targetSelector: '[data-tutorial="main-content"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 6,
      },
    ],
  },

  // ==================== LOGISTICA ====================
  {
    id: 'logistica-risorse',
    title: 'Logistica e Risorse',
    description: 'Mezzi, Attrezzature, Magazzino, Manutenzioni',
    icon: 'Truck',
    estimatedTime: '6 min',
    category: 'logistica',
    steps: [
      {
        id: 'intro',
        title: 'Modulo Logistica 🚛',
        description: 'Il modulo Logistica gestisce: Risorse e Mezzi (automezzi, attrezzature, macchinari), Magazzino materiali, Prenotazioni risorse, Documenti veicoli, Manutenzioni programmate, Segnalazioni guasti.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 8,
      },
      {
        id: 'nav-to-risorse',
        title: '👆 Clicca su "Risorse e Mezzi"',
        description: 'Nel menu laterale, sezione "Logistica", clicca sulla voce "Risorse e Mezzi". Qui gestisci tutto il parco mezzi e attrezzature aziendali.',
        targetSelector: '[data-tutorial="nav-risorse"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 4,
      },
      {
        id: 'risorse-list',
        title: '📋 Elenco Risorse',
        description: 'Tabella risorse: tipo (automezzo, attrezzatura, macchinario), targa/matricola, stato (disponibile, in uso, manutenzione), assegnazione corrente, prossima scadenza. Filtri per tipologia e stato.',
        targetSelector: '[data-tutorial="risorse-list"]',
        route: '/risorse',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 6,
      },
      {
        id: 'documenti-risorse',
        title: '📄 Tab Documenti Risorse',
        description: 'Documenti obbligatori per ogni risorsa: libretto circolazione, assicurazione RCA, revisione, tagliando, certificazioni. Alert automatici per scadenze. Veicolo con documenti scaduti = fermo.',
        targetSelector: '[data-tutorial="tab-documenti-risorse"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'manutenzioni-tab',
        title: '🔧 Tab Manutenzioni',
        description: 'Programma manutenzioni: ordinarie (tagliando, pneumatici) e straordinarie (riparazioni). Per ogni intervento: data, tipo, km, costo, officina. Storico completo per ogni risorsa.',
        targetSelector: '[data-tutorial="tab-manutenzioni"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'nav-to-magazzino',
        title: '📦 Clicca su "Magazzino"',
        description: 'Il modulo Magazzino gestisce: articoli con giacenze, movimenti (carico/scarico), sottoscorta, inventario. Collegato a cantieri per prelievi materiale.',
        targetSelector: '[data-tutorial="nav-magazzino"]',
        position: 'right',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'magazzino-overview',
        title: '📊 Panoramica Magazzino',
        description: 'Dashboard magazzino: valore totale, articoli sottoscorta, movimenti giornalieri. Tabella articoli con: codice, descrizione, giacenza, minimo, ubicazione. Alert per sottoscorta.',
        targetSelector: '[data-tutorial="magazzino-stats"]',
        route: '/magazzino',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 6,
      },
      {
        id: 'complete',
        title: 'Logistica Completata! 🎉',
        description: 'Ora conosci i moduli logistici. Usa il sistema per: monitorare scadenze veicoli, programmare manutenzioni, gestire scorte magazzino. Ricorda: veicoli con documenti scaduti non possono circolare!',
        targetSelector: '[data-tutorial="main-content"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 6,
      },
    ],
  },

  // ==================== COMPLIANCE ====================
  {
    id: 'compliance-iso-gdpr',
    title: 'Compliance ISO 9001 e GDPR',
    description: 'Sistema Qualità, Non Conformità, Audit, Privacy',
    icon: 'FileCheck',
    estimatedTime: '7 min',
    category: 'compliance',
    steps: [
      {
        id: 'intro',
        title: 'Moduli Compliance 📋',
        description: 'I moduli Compliance gestiscono: ISO 9001 (Sistema Gestione Qualità con NC, CAPA, Audit), ISO 14001 (Gestione Ambientale), GDPR (Privacy e protezione dati). Fondamentali per certificazioni e conformità normativa.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 8,
      },
      {
        id: 'nav-to-iso',
        title: '👆 Clicca su "ISO 9001"',
        description: 'Nel menu laterale, sezione "Compliance", clicca sulla voce "ISO 9001". Qui gestisci il Sistema Gestione Qualità secondo lo standard internazionale.',
        targetSelector: '[data-tutorial="nav-iso"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 4,
      },
      {
        id: 'iso-overview',
        title: '📊 Dashboard Qualità',
        description: 'KPI qualità: NC aperte, CAPA in corso, audit pianificati, indice qualità. Grafici andamento mensile. Alert per azioni scadute. Il dashboard riflette lo stato del SGQ.',
        targetSelector: '[data-tutorial="iso-stats"]',
        route: '/quality-iso',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 6,
      },
      {
        id: 'nc-tab',
        title: '❌ Tab Non Conformità',
        description: 'Registro NC: descrizione, gravità (minore/maggiore/critica), causa, azione correttiva, responsabile, scadenza, stato. Workflow: rilevata → analisi → azione → verifica → chiusa.',
        targetSelector: '[data-tutorial="tab-nc"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 7,
      },
      {
        id: 'capa-tab',
        title: '🔄 Tab CAPA',
        description: 'Azioni Correttive e Preventive: collegamento a NC, descrizione azione, responsabile, deadline, verifica efficacia. Fondamentali per il miglioramento continuo richiesto da ISO 9001.',
        targetSelector: '[data-tutorial="tab-capa"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'audit-tab',
        title: '🔍 Tab Audit Interni',
        description: 'Pianificazione e gestione audit: data, area/processo, auditor, checklist, rilievi, NC emerse. Report audit esportabile. Calendario audit annuale per pianificazione.',
        targetSelector: '[data-tutorial="tab-audit"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'nav-to-gdpr',
        title: '🔒 Clicca su "GDPR"',
        description: 'Il modulo GDPR gestisce: registro trattamenti, consensi, richieste interessati, data breach, DPIA. Fondamentale per la conformità al Regolamento Privacy europeo.',
        targetSelector: '[data-tutorial="nav-gdpr"]',
        position: 'right',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'gdpr-overview',
        title: '📊 Dashboard GDPR',
        description: 'Panoramica privacy: trattamenti attivi, consensi raccolti, richieste pendenti, data breach. Registro trattamenti con: finalità, base giuridica, categorie dati, periodo conservazione.',
        targetSelector: '[data-tutorial="gdpr-stats"]',
        route: '/gdpr-compliance',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 6,
      },
      {
        id: 'complete',
        title: 'Compliance Completata! 🎉',
        description: 'Ora conosci i moduli Compliance. Usa il sistema per: gestire NC e CAPA per ISO 9001, pianificare audit interni, mantenere il registro trattamenti GDPR. La compliance è fondamentale per certificazioni e tutela legale.',
        targetSelector: '[data-tutorial="main-content"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 7,
      },
    ],
  },

  // ==================== CONSUNTIVO/SAL ====================
  {
    id: 'consuntivo-sal',
    title: 'Consuntivo e SAL',
    description: 'Stato Avanzamento Lavori, Contratti, Previsioni',
    icon: 'TrendingUp',
    estimatedTime: '6 min',
    category: 'commesse',
    steps: [
      {
        id: 'intro',
        title: 'Modulo Consuntivo (SAL) 📈',
        description: 'Il modulo Consuntivo gestisce lo Stato Avanzamento Lavori: registrazione SAL periodici, collegamento a contratti, previsioni economiche, generazione documenti professionali su carta intestata.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 7,
      },
      {
        id: 'nav-to-sal',
        title: '👆 Clicca su "Consuntivo"',
        description: 'Nel menu laterale, sezione "Commesse", clicca sulla voce "Consuntivo". Qui gestisci tutti gli stati avanzamento lavori delle commesse.',
        targetSelector: '[data-tutorial="nav-sal"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 4,
      },
      {
        id: 'sal-overview',
        title: '📊 Panoramica SAL',
        description: 'Dashboard con: SAL registrati, importo totale avanzato, percentuale media, grafico confronto previsto/consuntivo. Filtri per cantiere, periodo, stato.',
        targetSelector: '[data-tutorial="sal-stats"]',
        route: '/consuntivo',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 6,
      },
      {
        id: 'sal-list',
        title: '📋 Elenco SAL',
        description: 'Tabella SAL: numero progressivo, data, cantiere, percentuale avanzamento, importo, stato (bozza, approvato, fatturato). Clicca per vedere/modificare dettagli.',
        targetSelector: '[data-tutorial="sal-list"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 5,
      },
      {
        id: 'new-sal-button',
        title: '➕ Nuovo SAL',
        description: 'Clicca per registrare un nuovo SAL: seleziona cantiere, inserisci data, percentuale avanzamento (o delta), importo, note. Il sistema calcola automaticamente gli importi in base al contratto.',
        targetSelector: '[data-tutorial="btn-new-sal"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'export-sal',
        title: '📄 Genera Documento SAL',
        description: 'Clicca "Esporta" per generare il documento SAL professionale: intestazione aziendale, dati cantiere/committente, tabella avanzamento, firme. Apre in nuova finestra per stampa/PDF.',
        targetSelector: '[data-tutorial="btn-export-sal"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'contratti-tab',
        title: '📝 Tab Contratti',
        description: 'Contratti collegati ai SAL: importo totale, date, clausole, penali. Il SAL si calcola come percentuale del contratto. Puoi creare contratti direttamente da qui.',
        targetSelector: '[data-tutorial="tab-contratti-sal"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'complete',
        title: 'Consuntivo Completato! 🎉',
        description: 'Ora sai gestire i SAL. Registra periodicamente gli avanzamenti per monitorare l\'andamento economico delle commesse. I documenti SAL generati sono pronti per invio al committente.',
        targetSelector: '[data-tutorial="sal-stats"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 6,
      },
    ],
  },

  // ==================== FORMAZIONE ====================
  {
    id: 'formazione-corsi',
    title: 'Gestione Formazione',
    description: 'Corsi, Attestati, Scadenze, Report',
    icon: 'GraduationCap',
    estimatedTime: '5 min',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Modulo Formazione 📚',
        description: 'Gestione centralizzata delle formazioni obbligatorie D.Lgs 81/08: corsi, attestati, scadenze, report. Monitora la compliance formativa di tutti i lavoratori con alert automatici.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 7,
      },
      {
        id: 'nav-to-formazione',
        title: '👆 Clicca su "Formazione"',
        description: 'Nel menu laterale, sezione "Sicurezza & HSE", clicca sulla voce "Formazione". Qui gestisci tutti i corsi e gli attestati del personale.',
        targetSelector: '[data-tutorial="nav-formazione"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 4,
      },
      {
        id: 'formazione-overview',
        title: '📊 Dashboard Formazione',
        description: 'Statistiche: formazioni valide, in scadenza, scadute. Calendario scadenze mensile. Alert per corsi da rinnovare. Il semaforo indica la compliance complessiva aziendale.',
        targetSelector: '[data-tutorial="formazione-stats"]',
        route: '/formazione',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 6,
      },
      {
        id: 'formazione-list',
        title: '📋 Elenco Formazioni',
        description: 'Tabella con tutte le formazioni: lavoratore, tipo corso, data conseguimento, scadenza, stato, attestato. Filtri per lavoratore, corso, stato. Ordinamento per scadenza.',
        targetSelector: '[data-tutorial="formazione-list"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 5,
      },
      {
        id: 'scadenze-view',
        title: '📅 Vista Scadenze',
        description: 'Calendario con tutte le scadenze formative: mese per mese, chi deve rinnovare cosa. Fondamentale per pianificare i corsi di aggiornamento in tempo.',
        targetSelector: '[data-tutorial="scadenze-calendar"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 5,
      },
      {
        id: 'complete',
        title: 'Formazione Completata! 🎉',
        description: 'Ora sai gestire le formazioni. Ricorda: formazione scaduta = lavoratore non può operare in cantiere. Pianifica i rinnovi con anticipo per evitare blocchi operativi e sanzioni.',
        targetSelector: '[data-tutorial="formazione-stats"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 6,
      },
    ],
  },

  // ==================== SCADENZARIO ====================
  {
    id: 'scadenzario-generale',
    title: 'Scadenzario Generale',
    description: 'Tutte le scadenze in un unico posto',
    icon: 'Calendar',
    estimatedTime: '4 min',
    category: 'principale',
    steps: [
      {
        id: 'intro',
        title: 'Scadenzario Centralizzato 📅',
        description: 'Lo Scadenzario raccoglie TUTTE le scadenze del sistema: documenti, formazioni, visite mediche, contratti, assicurazioni, manutenzioni. Vista unificata per non perdere nulla.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 7,
      },
      {
        id: 'nav-to-scadenzario',
        title: '👆 Clicca su "Scadenzario"',
        description: 'Nel menu laterale, sezione "Principale", clicca sulla voce "Scadenzario". Qui trovi tutte le scadenze organizzate per urgenza.',
        targetSelector: '[data-tutorial="nav-scadenzario"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 4,
      },
      {
        id: 'scadenzario-overview',
        title: '📊 Panoramica Scadenze',
        description: 'Statistiche: scadute (rosse), in scadenza 7gg (arancioni), in scadenza 30gg (gialle), ok (verdi). Ogni categoria è cliccabile per filtrare l\'elenco.',
        targetSelector: '[data-tutorial="scadenzario-stats"]',
        route: '/scadenzario',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
        readingTime: 6,
      },
      {
        id: 'scadenze-list',
        title: '📋 Elenco Scadenze',
        description: 'Tabella con: tipo scadenza, entità (lavoratore/impresa/risorsa), data scadenza, giorni rimanenti, priorità. Ordinata per urgenza. Azioni rapide per completare/rinnovare.',
        targetSelector: '[data-tutorial="scadenze-list"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 5,
      },
      {
        id: 'filters-scadenzario',
        title: '🔍 Filtri Scadenzario',
        description: 'Filtra per: tipo entità (lavoratore, impresa, risorsa), tipo scadenza (documento, formazione, visita), stato (scaduto, in scadenza, ok). I filtri aiutano a focalizzarti sulle priorità.',
        targetSelector: '[data-tutorial="filters"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 10,
        readingTime: 5,
      },
      {
        id: 'complete',
        title: 'Scadenzario Completato! 🎉',
        description: 'Usa lo scadenzario ogni giorno per identificare le priorità. Le scadenze rosse richiedono azione immediata. Imposta reminder email nelle Impostazioni per ricevere alert automatici.',
        targetSelector: '[data-tutorial="scadenzario-stats"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 6,
      },
    ],
  },

  // ==================== IMPOSTAZIONI ====================
  {
    id: 'impostazioni-sistema',
    title: 'Configurazione Sistema',
    description: 'Dati azienda, moduli, notifiche, sicurezza',
    icon: 'Settings',
    estimatedTime: '5 min',
    category: 'principale',
    steps: [
      {
        id: 'intro',
        title: 'Impostazioni Sistema ⚙️',
        description: 'Da Impostazioni configuri tutto il sistema: Dati Azienda (per intestazioni documenti), Documenti Azienda, Menu (moduli visibili), Generali (tema), Notifiche (email/push), Sicurezza (parametri HSE), Dati (export/import).',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
        readingTime: 9,
      },
      {
        id: 'nav-to-impostazioni',
        title: '👆 Clicca su "Impostazioni"',
        description: 'Nel menu utente in alto a destra, oppure nel menu laterale, clicca su "Impostazioni". Qui configuri tutti i parametri del sistema.',
        targetSelector: '[data-tutorial="nav-impostazioni"]',
        position: 'bottom',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
        readingTime: 4,
      },
      {
        id: 'tab-dati-azienda',
        title: '🏢 Tab Dati Azienda',
        description: 'Compila tutti i dati societari: ragione sociale, P.IVA, indirizzo, telefono, email, PEC. Questi dati appaiono nell\'intestazione di TUTTI i documenti generati dal sistema.',
        targetSelector: '[data-tutorial="tab-dati-azienda"]',
        route: '/impostazioni',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'upload-logo',
        title: '🖼️ Logo e Timbro',
        description: 'Carica il logo aziendale (appare in intestazione documenti) e il timbro digitale (appare nei documenti che richiedono timbro). Formati supportati: PNG, JPG. Dimensione consigliata: 200x80px per logo.',
        targetSelector: '[data-tutorial="upload-logo"]',
        position: 'right',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'tab-menu',
        title: '📋 Tab Menu',
        description: 'Personalizza i moduli visibili nel menu laterale. Disattiva i moduli che non usi per semplificare l\'interfaccia. Puoi riattivare tutto in qualsiasi momento.',
        targetSelector: '[data-tutorial="tab-menu"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'tab-notifiche',
        title: '🔔 Tab Notifiche',
        description: 'Configura le notifiche: email per scadenze (quanti giorni prima), notifiche push per task, alert critici. Imposta la frequenza dei digest email (giornaliero/settimanale).',
        targetSelector: '[data-tutorial="tab-notifiche"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 5,
      },
      {
        id: 'tab-sicurezza-params',
        title: '🔒 Tab Sicurezza',
        description: 'Parametri HSE: soglia "in scadenza" (30gg default), soglia "critico" (7gg default), documenti obbligatori per imprese. Questi parametri determinano i colori dei semafori in tutto il sistema.',
        targetSelector: '[data-tutorial="tab-sicurezza"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
        readingTime: 6,
      },
      {
        id: 'complete',
        title: 'Impostazioni Completate! 🎉',
        description: 'Hai configurato il sistema. Ricorda di salvare dopo ogni modifica. I dati azienda sono fondamentali per la generazione documenti. Rivedi periodicamente le impostazioni notifiche.',
        targetSelector: '[data-tutorial="main-content"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
        readingTime: 6,
      },
    ],
  },
];
