// Tutorial step definitions for interactive guided tours
// TUTORIAL INTERATTIVI - Cursor animato + Spotlight su OGNI step

export interface TutorialStep {
  id: string;
  title: string;
  description: string;
  targetSelector?: string;
  route?: string;
  position?: 'top' | 'bottom' | 'left' | 'right' | 'center';
  action?: 'click' | 'type' | 'scroll' | 'hover' | 'wait';
  actionDelay?: number;
  highlightPadding?: number;
  cursorOffset?: { x: number; y: number };
}

export interface Tutorial {
  id: string;
  title: string;
  description: string;
  icon: string;
  estimatedTime: string;
  category: 'principale' | 'commesse' | 'hse' | 'commerciale' | 'amministrazione' | 'logistica' | 'compliance';
  steps: TutorialStep[];
}

export const tutorials: Tutorial[] = [
  // ==================== PRINCIPALE ====================
  {
    id: 'dashboard-tour',
    title: 'Tour Dashboard',
    description: 'Panoramica completa della dashboard',
    icon: 'LayoutDashboard',
    estimatedTime: '3 min',
    category: 'principale',
    steps: [
      {
        id: 'intro',
        title: 'Benvenuto in Gest-e! 👋',
        description: 'La Dashboard mostra in tempo reale: cantieri attivi, alert sicurezza, scadenze e task.',
        targetSelector: '[data-tutorial="main-content"]',
        position: 'center',
        route: '/dashboard',
        action: 'wait',
        highlightPadding: 50,
      },
      {
        id: 'stat-cards',
        title: '📊 Statistiche Rapide',
        description: 'Card con KPI principali. Clicca per vedere i dettagli di ogni metrica.',
        targetSelector: '[data-tutorial="stat-cards"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'sidebar',
        title: '📂 Menu Navigazione',
        description: 'Organizzato per reparti. Clicca per espandere le sezioni.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        action: 'click',
        highlightPadding: 10,
      },
      {
        id: 'search',
        title: '🔍 Ricerca Globale (Ctrl+K)',
        description: 'Cerca ovunque: commesse, lavoratori, imprese, documenti.',
        targetSelector: '[data-tutorial="global-search"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'notifications',
        title: '🔔 Centro Notifiche',
        description: 'Scadenze documenti, task assegnate, alert critici.',
        targetSelector: '[data-tutorial="notifications"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'critical-alerts',
        title: '⚠️ Alert Critici',
        description: 'Badge rosso = documenti scaduti o non conformità. Risolvi subito.',
        targetSelector: '[data-tutorial="critical-alerts"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 8,
      },
      {
        id: 'user-menu',
        title: '👤 Menu Utente',
        description: 'Profilo, Impostazioni, Dati Azienda, Logout.',
        targetSelector: '[data-tutorial="user-menu"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'Dashboard Completata! ✨',
        description: 'Ora conosci tutti gli elementi. Prosegui con altri tutorial!',
        targetSelector: '[data-tutorial="main-content"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 50,
      },
    ],
  },
  {
    id: 'projects-kanban',
    title: 'Gestione Progetti Kanban',
    description: 'Board Kanban, vista tabella, timeline Gantt e calendario',
    icon: 'FolderKanban',
    estimatedTime: '4 min',
    category: 'principale',
    steps: [
      {
        id: 'intro',
        title: 'Modulo Progetti 📋',
        description: 'Gestisci task con: Board Kanban, Tabella, Timeline Gantt, Calendario.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-progetti',
        title: 'Clicca su Progetti',
        description: 'Nel menu laterale, clicca "Progetti" per accedere al modulo.',
        targetSelector: '[data-tutorial="nav-progetti"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'progetti-page',
        title: 'Pagina Progetti',
        description: 'In alto: statistiche, filtri, ricerca, selettore vista.',
        targetSelector: '[data-tutorial="page-header"]',
        route: '/progetti',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'view-tabs',
        title: '👁️ Quattro Viste',
        description: 'Kanban | Tabella | Timeline | Calendario. Clicca per cambiare.',
        targetSelector: '[data-tutorial="view-tabs"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 10,
      },
      {
        id: 'kanban-columns',
        title: '📊 Colonne Kanban',
        description: 'Da Fare → In Corso → Revisione → Fatto. Trascina per cambiare stato.',
        targetSelector: '[data-tutorial="kanban-columns"]',
        position: 'top',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'new-task',
        title: '➕ Nuova Task',
        description: 'Clicca qui per creare una nuova task con titolo, descrizione, priorità.',
        targetSelector: '[data-tutorial="btn-new-task"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'Kanban Completato! 🎉',
        description: 'Usa le viste per gestire i tuoi progetti quotidianamente.',
        targetSelector: '[data-tutorial="kanban-columns"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },

  // ==================== COMMESSE ====================
  {
    id: 'create-commessa',
    title: 'Creare una Commessa',
    description: 'Creazione completa: anagrafica, committente, importo, date',
    icon: 'Briefcase',
    estimatedTime: '5 min',
    category: 'commesse',
    steps: [
      {
        id: 'intro',
        title: 'Cos\'è una Commessa? 🏗️',
        description: 'Entità centrale con anagrafica, dati economici, figure responsabili.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-cantieri',
        title: 'Clicca su Commesse',
        description: 'Nel menu laterale, sezione Commesse, clicca "Commesse".',
        targetSelector: '[data-tutorial="nav-cantieri"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'cantieri-page',
        title: 'Elenco Commesse',
        description: 'Card con: semaforo stato, nome, committente, importo, SAL.',
        targetSelector: '[data-tutorial="cantieri-list"]',
        route: '/cantieri',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'click-new',
        title: '➕ Nuova Commessa',
        description: 'Clicca questo pulsante per aprire il form di creazione.',
        targetSelector: '[data-tutorial="btn-nuovo-cantiere"]',
        position: 'bottom',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'fill-form-intro',
        title: '📝 Modulo Creazione',
        description: 'Compila i campi: Dati, Committente, Ubicazione, Date, Importo.',
        targetSelector: '[data-tutorial="form-cantiere"]',
        position: 'left',
        action: 'hover',
        highlightPadding: 20,
      },
      {
        id: 'field-nome',
        title: '📌 Nome Commessa',
        description: 'Inserisci un nome descrittivo e univoco per la commessa.',
        targetSelector: '[data-tutorial="field-nome"]',
        position: 'right',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'field-codice',
        title: '🔢 Codice Commessa',
        description: 'ID univoco. Formato consigliato: COM-2025-001',
        targetSelector: '[data-tutorial="field-codice"]',
        position: 'right',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'field-importo',
        title: '💰 Importo Contratto',
        description: 'Valore economico totale per calcolo SAL e fatturazione.',
        targetSelector: '[data-tutorial="field-importo"]',
        position: 'right',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'field-responsabile',
        title: '👷 Figure Responsabili',
        description: 'DL, CSP, CSE, RSPP. Obbligatori per D.Lgs 81/08.',
        targetSelector: '[data-tutorial="field-responsabile"]',
        position: 'right',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'save-form',
        title: '💾 Salva Commessa',
        description: 'Clicca per salvare. Verifica automatica campi obbligatori.',
        targetSelector: '[data-tutorial="btn-salva-cantiere"]',
        position: 'top',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'Commessa Creata! 🎉',
        description: 'Prossimi passi: assegna imprese, lavoratori, carica documenti.',
        targetSelector: '[data-tutorial="cantieri-list"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'manage-commessa-detail',
    title: 'Dettaglio Commessa',
    description: 'Panoramica, imprese, lavoratori, documenti, SAL',
    icon: 'FileText',
    estimatedTime: '4 min',
    category: 'commesse',
    steps: [
      {
        id: 'intro',
        title: 'Centro di Controllo 📋',
        description: 'Da qui gestisci: panoramica, imprese, lavoratori, documenti, SAL.',
        targetSelector: '[data-tutorial="cantieri-list"]',
        position: 'bottom',
        route: '/cantieri',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'select-commessa',
        title: '👆 Seleziona Commessa',
        description: 'Clicca su una card per accedere ai dettagli.',
        targetSelector: '[data-tutorial="cantiere-card"]',
        position: 'right',
        action: 'click',
        highlightPadding: 10,
      },
      {
        id: 'detail-header',
        title: '📊 Intestazione',
        description: 'Nome, stato, committente, importo, date, barra SAL.',
        targetSelector: '[data-tutorial="detail-header"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'tabs-navigation',
        title: '📑 Tab Navigazione',
        description: 'Clicca sui tab: Panoramica, Imprese, Lavoratori, Documenti, SAL.',
        targetSelector: '[data-tutorial="detail-tabs"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 10,
      },
      {
        id: 'tab-imprese',
        title: '🏢 Tab Imprese',
        description: 'Clicca per vedere i subappaltatori assegnati.',
        targetSelector: '[data-tutorial="tab-imprese"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'tab-lavoratori',
        title: '👷 Tab Lavoratori',
        description: 'Clicca per vedere il personale operante.',
        targetSelector: '[data-tutorial="tab-lavoratori"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'tab-documenti',
        title: '📄 Tab Documenti',
        description: 'Clicca per gestire POS, PSC, autorizzazioni.',
        targetSelector: '[data-tutorial="tab-documenti"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'tab-sal',
        title: '📈 Tab SAL',
        description: 'Clicca per vedere l\'avanzamento lavori.',
        targetSelector: '[data-tutorial="tab-sal"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'Dettaglio Completato! ✨',
        description: 'Usa i tab per gestire ogni aspetto della commessa.',
        targetSelector: '[data-tutorial="detail-header"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },

  // ==================== HSE ====================
  {
    id: 'manage-lavoratori',
    title: 'Gestione Lavoratori',
    description: 'Anagrafica, formazioni, visite mediche, DPI',
    icon: 'Users',
    estimatedTime: '5 min',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Anagrafica Lavoratori 👷',
        description: 'Gestione completa: dati, formazioni, visite mediche, DPI.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-lavoratori',
        title: 'Clicca su Lavoratori',
        description: 'Nel menu Sicurezza & HSE, clicca "Lavoratori".',
        targetSelector: '[data-tutorial="nav-lavoratori"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'lavoratori-page',
        title: 'Elenco Lavoratori',
        description: 'Tabella con: nome, impresa, mansione, semaforo compliance.',
        targetSelector: '[data-tutorial="lavoratori-list"]',
        route: '/lavoratori',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'traffic-light',
        title: '🚦 Sistema Semaforo',
        description: '🟢 OK | 🟡 In scadenza | 🔴 Scaduto = NON può lavorare.',
        targetSelector: '[data-tutorial="traffic-light"]',
        position: 'right',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'new-lavoratore',
        title: '➕ Nuovo Lavoratore',
        description: 'Clicca per aggiungere un nuovo lavoratore all\'anagrafica.',
        targetSelector: '[data-tutorial="btn-nuovo-lavoratore"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'formazioni',
        title: '📚 Formazioni',
        description: 'Clicca per gestire i corsi obbligatori del lavoratore.',
        targetSelector: '[data-tutorial="tab-formazioni"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'visite-mediche',
        title: '🏥 Visite Mediche',
        description: 'Clicca per gestire le visite e i giudizi di idoneità.',
        targetSelector: '[data-tutorial="tab-visite"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'Lavoratori Completato! 🎉',
        description: 'Monitora sempre il semaforo per evitare sanzioni.',
        targetSelector: '[data-tutorial="lavoratori-list"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'manage-imprese',
    title: 'Gestione Imprese',
    description: 'Subappaltatori, DURC, Visura, documenti',
    icon: 'Building2',
    estimatedTime: '4 min',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Anagrafica Imprese 🏢',
        description: 'Gestione subappaltatori: dati, documenti, rating, assegnazioni.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-imprese',
        title: 'Clicca su Imprese',
        description: 'Nel menu Sicurezza & HSE, clicca "Imprese".',
        targetSelector: '[data-tutorial="nav-imprese"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'imprese-page',
        title: 'Elenco Imprese',
        description: 'Ragione sociale, P.IVA, tipo, semaforo documenti, rating.',
        targetSelector: '[data-tutorial="imprese-list"]',
        route: '/imprese',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'new-impresa',
        title: '➕ Nuova Impresa',
        description: 'Clicca per aggiungere un nuovo subappaltatore.',
        targetSelector: '[data-tutorial="btn-nuova-impresa"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'documenti-impresa',
        title: '📄 Documenti',
        description: 'DURC, Visura, Polizza RCT/O. Clicca per caricare.',
        targetSelector: '[data-tutorial="docs-impresa"]',
        position: 'right',
        action: 'click',
        highlightPadding: 10,
      },
      {
        id: 'complete',
        title: 'Imprese Completato! ✨',
        description: 'Impresa con 🔴 non può essere assegnata a cantieri.',
        targetSelector: '[data-tutorial="imprese-list"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'formazione-sicurezza',
    title: 'Formazione Sicurezza',
    description: 'Corsi obbligatori, scadenze, attestati',
    icon: 'GraduationCap',
    estimatedTime: '4 min',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Formazione D.Lgs 81/08 📚',
        description: 'Art. 37: formazione obbligatoria per tutti i lavoratori.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-formazione',
        title: 'Clicca su Formazione',
        description: 'Nel menu Sicurezza & HSE, clicca "Formazione".',
        targetSelector: '[data-tutorial="nav-formazione"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'formazione-page',
        title: 'Dashboard Formazione',
        description: 'Statistiche: in regola, in scadenza, scaduti. Calendario.',
        targetSelector: '[data-tutorial="formazione-stats"]',
        route: '/formazione',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'tipi-corsi',
        title: '📋 Tipologie Corsi',
        description: 'Base 16h, Specifica, Preposti, Antincendio, Primo Soccorso.',
        targetSelector: '[data-tutorial="tipi-corsi"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'registra-corso',
        title: '➕ Registra Formazione',
        description: 'Clicca per registrare un nuovo corso completato.',
        targetSelector: '[data-tutorial="btn-nuova-formazione"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'Formazione Completata! 🎉',
        description: 'Sanzioni €1.200-€5.200 per lavoratore non formato.',
        targetSelector: '[data-tutorial="formazione-stats"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'sorveglianza-sanitaria',
    title: 'Sorveglianza Sanitaria',
    description: 'Visite mediche, idoneità, protocollo sanitario',
    icon: 'Stethoscope',
    estimatedTime: '4 min',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Visite Mediche 🏥',
        description: 'Art. 41 D.Lgs 81/08: sorveglianza sanitaria obbligatoria.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-visite',
        title: 'Clicca su Sorveglianza',
        description: 'Nel menu Sicurezza & HSE, clicca "Sorveglianza Sanitaria".',
        targetSelector: '[data-tutorial="nav-sorveglianza"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'visite-page',
        title: 'Dashboard Visite',
        description: 'Calendario visite, elenco per lavoratore, alert scadenze.',
        targetSelector: '[data-tutorial="visite-stats"]',
        route: '/sorveglianza-sanitaria',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'tipi-visite',
        title: '📋 Tipologie Visite',
        description: 'Preventiva, Periodica, Cambio mansione, Rientro malattia.',
        targetSelector: '[data-tutorial="tipi-visite"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'giudizi',
        title: '✅ Giudizi Idoneità',
        description: 'Idoneo, con prescrizioni, con limitazioni, non idoneo.',
        targetSelector: '[data-tutorial="giudizi"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nuova-visita',
        title: '➕ Nuova Visita',
        description: 'Clicca per programmare una nuova visita medica.',
        targetSelector: '[data-tutorial="btn-nuova-visita"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'Sorveglianza Completata! ✨',
        description: 'Lavoratore senza idoneità = non può lavorare.',
        targetSelector: '[data-tutorial="visite-stats"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'dpi-management',
    title: 'Gestione DPI',
    description: 'Consegna, scadenze, registro',
    icon: 'HardHat',
    estimatedTime: '3 min',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'DPI - Dispositivi Protezione 🦺',
        description: 'Art. 77 D.Lgs 81/08: obbligo fornitura e registro consegne.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-dpi',
        title: 'Clicca su DPI',
        description: 'Nel menu Sicurezza & HSE, clicca "DPI".',
        targetSelector: '[data-tutorial="nav-dpi"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'dpi-page',
        title: 'Registro DPI',
        description: 'Elenco consegne per lavoratore. Tipo, data, scadenza.',
        targetSelector: '[data-tutorial="dpi-list"]',
        route: '/dpi',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'nuova-consegna',
        title: '➕ Registra Consegna',
        description: 'Clicca per registrare una nuova consegna DPI.',
        targetSelector: '[data-tutorial="btn-nuovo-dpi"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'DPI Completato! 🎉',
        description: 'Il registro DPI firmato è documento obbligatorio.',
        targetSelector: '[data-tutorial="dpi-list"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'checkin-cantiere',
    title: 'Check-in Sicurezza',
    description: 'Verifica quotidiana cantiere, briefing, DPI',
    icon: 'ClipboardCheck',
    estimatedTime: '3 min',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Check-in Giornaliero ✅',
        description: 'Verifica quotidiana inizio lavori: DPI, meteo, briefing.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-checkin',
        title: 'Clicca su Check-in',
        description: 'Nel menu Sicurezza & HSE, clicca "Check-in Sicurezza".',
        targetSelector: '[data-tutorial="nav-checkin"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'checkin-page',
        title: 'Storico Check-in',
        description: 'Elenco check-in per data/cantiere. Visualizza dettagli.',
        targetSelector: '[data-tutorial="checkin-list"]',
        route: '/checkin-sicurezza',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'nuovo-checkin',
        title: '➕ Nuovo Check-in',
        description: 'Clicca per eseguire il check-in giornaliero.',
        targetSelector: '[data-tutorial="btn-nuovo-checkin"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'Check-in Completato! ✨',
        description: 'Fai check-in ogni mattina. Prova di diligenza.',
        targetSelector: '[data-tutorial="checkin-list"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },

  // ==================== COMMERCIALE ====================
  {
    id: 'ufficio-commerciale',
    title: 'Ufficio Commerciale CRM',
    description: 'Lead, pipeline vendita, preventivi',
    icon: 'Handshake',
    estimatedTime: '4 min',
    category: 'commerciale',
    steps: [
      {
        id: 'intro',
        title: 'CRM Commerciale 📊',
        description: 'Gestione lead, pipeline vendita, preventivi, contratti.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-commerciale',
        title: 'Clicca su Commerciale',
        description: 'Nel menu Ufficio Commerciale, clicca "CRM".',
        targetSelector: '[data-tutorial="nav-commerciale"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'commerciale-page',
        title: 'Dashboard CRM',
        description: 'Pipeline visiva, lead attivi, preventivi in attesa.',
        targetSelector: '[data-tutorial="crm-dashboard"]',
        route: '/ufficio-commerciale',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'pipeline',
        title: '🎯 Pipeline Vendita',
        description: 'Trascina i lead tra gli stadi della pipeline.',
        targetSelector: '[data-tutorial="pipeline"]',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nuovo-lead',
        title: '➕ Nuovo Lead',
        description: 'Clicca per aggiungere un nuovo potenziale cliente.',
        targetSelector: '[data-tutorial="btn-nuovo-lead"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'CRM Completato! 🎉',
        description: 'Aggiorna la pipeline regolarmente per non perdere opportunità.',
        targetSelector: '[data-tutorial="crm-dashboard"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'listino-prezzi',
    title: 'Listino Prezzi',
    description: 'Articoli, prezzi, categorie, margini',
    icon: 'Euro',
    estimatedTime: '3 min',
    category: 'commerciale',
    steps: [
      {
        id: 'intro',
        title: 'Listino Prezzi 💶',
        description: 'Catalogo articoli con prezzi, costi, margini.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-listino',
        title: 'Clicca su Listino',
        description: 'Nel menu Commerciale, clicca "Listino Prezzi".',
        targetSelector: '[data-tutorial="nav-listino"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'listino-page',
        title: 'Catalogo Articoli',
        description: 'Codice, descrizione, unità, prezzo, costo, margine.',
        targetSelector: '[data-tutorial="listino-table"]',
        route: '/listino-prezzi',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'nuovo-articolo',
        title: '➕ Nuovo Articolo',
        description: 'Clicca per aggiungere un nuovo articolo al listino.',
        targetSelector: '[data-tutorial="btn-nuovo-articolo"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'Listino Completato! ✨',
        description: 'Mantieni i prezzi aggiornati per preventivi accurati.',
        targetSelector: '[data-tutorial="listino-table"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },

  // ==================== AMMINISTRAZIONE ====================
  {
    id: 'computo-metrico',
    title: 'Computo Metrico',
    description: 'Voci, quantità, prezzi, totali',
    icon: 'Calculator',
    estimatedTime: '4 min',
    category: 'amministrazione',
    steps: [
      {
        id: 'intro',
        title: 'Computo Metrico 📐',
        description: 'Calcolo dettagliato costi lavori. Collegato a listino.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-computo',
        title: 'Clicca su Computo',
        description: 'Nel menu Amministrazione, clicca "Computo Metrico".',
        targetSelector: '[data-tutorial="nav-computo"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'computo-page',
        title: 'Lista Computi',
        description: 'Computi per commessa. Stato e totale calcolato.',
        targetSelector: '[data-tutorial="computi-list"]',
        route: '/computo-metrico',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'nuovo-computo',
        title: '➕ Nuovo Computo',
        description: 'Clicca per creare un nuovo computo metrico.',
        targetSelector: '[data-tutorial="btn-nuovo-computo"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'aggiungi-voci',
        title: '📝 Aggiungi Voci',
        description: 'Seleziona articoli da listino, specifica quantità.',
        targetSelector: '[data-tutorial="btn-aggiungi-voce"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'Computo Completato! 🎉',
        description: 'Esporta in Excel o PDF per presentazione.',
        targetSelector: '[data-tutorial="computi-list"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'gestione-sal',
    title: 'SAL - Avanzamento Lavori',
    description: 'Registrazione, grafico, confronto',
    icon: 'TrendingUp',
    estimatedTime: '3 min',
    category: 'amministrazione',
    steps: [
      {
        id: 'intro',
        title: 'SAL - Stato Avanzamento 📈',
        description: 'Registra avanzamento economico. Base per fatturazione.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-sal',
        title: 'Clicca su SAL',
        description: 'Nel menu Commesse, clicca "SAL".',
        targetSelector: '[data-tutorial="nav-sal"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'sal-page',
        title: 'Dashboard SAL',
        description: 'Grafico cumulativo per commessa. Previsto vs consuntivo.',
        targetSelector: '[data-tutorial="sal-chart"]',
        route: '/sal',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'nuovo-sal',
        title: '➕ Nuovo SAL',
        description: 'Clicca per registrare un nuovo stato avanzamento.',
        targetSelector: '[data-tutorial="btn-nuovo-sal"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'SAL Completato! ✨',
        description: 'Registra SAL regolarmente per monitorare l\'andamento.',
        targetSelector: '[data-tutorial="sal-chart"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'rapportini-lavoro',
    title: 'Rapportini Giornalieri',
    description: 'Giornale lavori, ore, materiali',
    icon: 'FileEdit',
    estimatedTime: '3 min',
    category: 'amministrazione',
    steps: [
      {
        id: 'intro',
        title: 'Rapportini Lavoro 📝',
        description: 'Documenta ogni giornata: personale, ore, lavorazioni.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-rapportini',
        title: 'Clicca su Rapportini',
        description: 'Nel menu Commesse, clicca "Rapportini".',
        targetSelector: '[data-tutorial="nav-rapportini"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'rapportini-page',
        title: 'Elenco Rapportini',
        description: 'Storico per data/commessa. Dettaglio completo.',
        targetSelector: '[data-tutorial="rapportini-list"]',
        route: '/rapportini',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'nuovo-rapportino',
        title: '➕ Nuovo Rapportino',
        description: 'Clicca per compilare il rapportino giornaliero.',
        targetSelector: '[data-tutorial="btn-nuovo-rapportino"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'Rapportini Completato! 🎉',
        description: 'Compila rapportino ogni sera. Documentazione legale.',
        targetSelector: '[data-tutorial="rapportini-list"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },

  // ==================== LOGISTICA ====================
  {
    id: 'gestione-risorse',
    title: 'Risorse e Mezzi',
    description: 'Veicoli, attrezzature, manutenzioni',
    icon: 'Truck',
    estimatedTime: '4 min',
    category: 'logistica',
    steps: [
      {
        id: 'intro',
        title: 'Parco Mezzi 🚛',
        description: 'Gestione veicoli e attrezzature: documenti, manutenzioni.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-risorse',
        title: 'Clicca su Risorse',
        description: 'Nel menu Logistica, clicca "Risorse/Mezzi".',
        targetSelector: '[data-tutorial="nav-risorse"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'risorse-page',
        title: 'Elenco Risorse',
        description: 'Veicoli, macchinari. Stato e scadenze documenti.',
        targetSelector: '[data-tutorial="risorse-list"]',
        route: '/risorse',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'manutenzioni',
        title: '🔧 Piano Manutenzioni',
        description: 'Clicca per vedere le manutenzioni programmate.',
        targetSelector: '[data-tutorial="tab-manutenzioni"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'nuova-risorsa',
        title: '➕ Nuova Risorsa',
        description: 'Clicca per aggiungere un nuovo mezzo o attrezzatura.',
        targetSelector: '[data-tutorial="btn-nuova-risorsa"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'Risorse Completato! ✨',
        description: 'Mezzi in ordine = sicurezza + efficienza.',
        targetSelector: '[data-tutorial="risorse-list"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'gestione-magazzino',
    title: 'Magazzino',
    description: 'Articoli, giacenze, movimenti',
    icon: 'Warehouse',
    estimatedTime: '3 min',
    category: 'logistica',
    steps: [
      {
        id: 'intro',
        title: 'Gestione Magazzino 📦',
        description: 'Inventario materiali: giacenze, movimenti, soglie minime.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-magazzino',
        title: 'Clicca su Magazzino',
        description: 'Nel menu Logistica, clicca "Magazzino".',
        targetSelector: '[data-tutorial="nav-magazzino"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'magazzino-page',
        title: 'Inventario',
        description: 'Codice, descrizione, giacenza, scorta minima, ubicazione.',
        targetSelector: '[data-tutorial="magazzino-list"]',
        route: '/magazzino',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'movimenti',
        title: '📊 Movimenti',
        description: 'Clicca per vedere carico, scarico, storico.',
        targetSelector: '[data-tutorial="tab-movimenti"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'nuovo-articolo',
        title: '➕ Nuovo Articolo',
        description: 'Clicca per aggiungere un nuovo articolo.',
        targetSelector: '[data-tutorial="btn-nuovo-articolo-mag"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'Magazzino Completato! 🎉',
        description: 'Imposta soglie minime per alert sottoscorta.',
        targetSelector: '[data-tutorial="magazzino-list"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'gestione-ddt',
    title: 'DDT - Documenti Trasporto',
    description: 'Creazione, stampa, gestione DDT',
    icon: 'FileText',
    estimatedTime: '3 min',
    category: 'logistica',
    steps: [
      {
        id: 'intro',
        title: 'DDT - Trasporto 🚚',
        description: 'Documenti di Trasporto digitali. Numerazione automatica.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-ddt',
        title: 'Clicca su DDT',
        description: 'Nel menu Logistica o da Magazzino → DDT.',
        targetSelector: '[data-tutorial="nav-ddt"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'ddt-page',
        title: 'Elenco DDT',
        description: 'Numero, data, mittente, destinatario, stato.',
        targetSelector: '[data-tutorial="ddt-list"]',
        route: '/magazzino',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'nuovo-ddt',
        title: '➕ Nuovo DDT',
        description: 'Clicca per creare un nuovo documento di trasporto.',
        targetSelector: '[data-tutorial="btn-nuovo-ddt"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'DDT Completato! ✨',
        description: 'DDT = prova consegna. Stampa copia per firma.',
        targetSelector: '[data-tutorial="ddt-list"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },

  // ==================== COMPLIANCE ====================
  {
    id: 'gdpr-compliance',
    title: 'GDPR Privacy',
    description: 'Registro trattamenti, informative, consensi',
    icon: 'Shield',
    estimatedTime: '4 min',
    category: 'compliance',
    steps: [
      {
        id: 'intro',
        title: 'GDPR - Privacy 🔒',
        description: 'Conformità Regolamento UE 2016/679. Documenti obbligatori.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-gdpr',
        title: 'Clicca su GDPR',
        description: 'Nel menu Conformità, clicca "GDPR Privacy".',
        targetSelector: '[data-tutorial="nav-gdpr"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'gdpr-page',
        title: 'Dashboard GDPR',
        description: 'Checklist conformità, documenti, stato implementazione.',
        targetSelector: '[data-tutorial="gdpr-dashboard"]',
        route: '/gdpr-compliance',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'documenti-gdpr',
        title: '📄 Documenti',
        description: 'Clicca per generare registro, informative, consensi.',
        targetSelector: '[data-tutorial="docs-gdpr"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 10,
      },
      {
        id: 'complete',
        title: 'GDPR Completato! ✨',
        description: 'Sanzioni fino a €20M o 4% fatturato. Mantieni aggiornato.',
        targetSelector: '[data-tutorial="gdpr-dashboard"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'iso-9001',
    title: 'ISO 9001 Qualità',
    description: 'Sistema gestione qualità, procedure, audit',
    icon: 'Award',
    estimatedTime: '4 min',
    category: 'compliance',
    steps: [
      {
        id: 'intro',
        title: 'ISO 9001 - Qualità 🏆',
        description: 'Sistema Gestione Qualità: politica, obiettivi, procedure.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-iso9001',
        title: 'Clicca su ISO 9001',
        description: 'Nel menu Conformità, clicca "ISO 9001".',
        targetSelector: '[data-tutorial="nav-iso9001"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'iso-page',
        title: 'Dashboard ISO 9001',
        description: 'Stato certificazione, scadenze audit, documenti sistema.',
        targetSelector: '[data-tutorial="iso-dashboard"]',
        route: '/quality-iso',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'documenti-iso',
        title: '📄 Documenti SGQ',
        description: 'Clicca per gestire procedure, istruzioni, moduli.',
        targetSelector: '[data-tutorial="docs-iso"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 10,
      },
      {
        id: 'complete',
        title: 'ISO 9001 Completato! 🎉',
        description: 'ISO 9001 = vantaggio competitivo + requisito gare.',
        targetSelector: '[data-tutorial="iso-dashboard"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'iso-14001',
    title: 'ISO 14001 Ambiente',
    description: 'Gestione ambientale, aspetti, impatti',
    icon: 'Leaf',
    estimatedTime: '3 min',
    category: 'compliance',
    steps: [
      {
        id: 'intro',
        title: 'ISO 14001 - Ambiente 🌿',
        description: 'Sistema Gestione Ambientale: aspetti, impatti, controlli.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-iso14001',
        title: 'Clicca su ISO 14001',
        description: 'Nel menu Conformità, clicca "ISO 14001".',
        targetSelector: '[data-tutorial="nav-iso14001"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'iso-page',
        title: 'Dashboard ISO 14001',
        description: 'Analisi ambientale, registro aspetti, indicatori.',
        targetSelector: '[data-tutorial="iso-env-dashboard"]',
        route: '/environmental-iso',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'aspetti-ambientali',
        title: '🌍 Aspetti Ambientali',
        description: 'Clicca per gestire il registro aspetti e impatti.',
        targetSelector: '[data-tutorial="aspetti-ambientali"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 10,
      },
      {
        id: 'complete',
        title: 'ISO 14001 Completato! ✨',
        description: 'ISO 14001 = sostenibilità + punteggio gare CAM.',
        targetSelector: '[data-tutorial="iso-env-dashboard"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
  {
    id: 'dlgs-81-08',
    title: 'D.Lgs 81/08 Sicurezza',
    description: 'DVR, procedure, moduli sicurezza lavoro',
    icon: 'ShieldCheck',
    estimatedTime: '4 min',
    category: 'compliance',
    steps: [
      {
        id: 'intro',
        title: 'D.Lgs 81/08 - Sicurezza ⚠️',
        description: 'Testo Unico Sicurezza: DVR, procedure, moduli obbligatori.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
        route: '/dashboard',
        action: 'hover',
        highlightPadding: 10,
      },
      {
        id: 'nav-dlgs',
        title: 'Clicca su D.Lgs 81/08',
        description: 'Nel menu Conformità, clicca "D.Lgs 81/08".',
        targetSelector: '[data-tutorial="nav-dlgs81"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
        highlightPadding: 8,
      },
      {
        id: 'dlgs-page',
        title: 'Dashboard Sicurezza',
        description: 'Documenti: DVR, DUVRI, POS, PSC. Moduli e verbali.',
        targetSelector: '[data-tutorial="dlgs-dashboard"]',
        route: '/safety-dlgs81',
        position: 'bottom',
        action: 'hover',
        highlightPadding: 15,
      },
      {
        id: 'documenti-sicurezza',
        title: '📄 Documenti Obbligatori',
        description: 'Clicca per gestire DVR, POS, DUVRI, verbali.',
        targetSelector: '[data-tutorial="docs-sicurezza"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 10,
      },
      {
        id: 'genera-pos',
        title: '📝 Genera POS',
        description: 'Clicca per creare un Piano Operativo di Sicurezza.',
        targetSelector: '[data-tutorial="btn-genera-pos"]',
        position: 'bottom',
        action: 'click',
        highlightPadding: 8,
      },
      {
        id: 'complete',
        title: 'D.Lgs 81/08 Completato! 🎉',
        description: 'Responsabilità penale. Sanzioni fino €6.400 + arresto.',
        targetSelector: '[data-tutorial="dlgs-dashboard"]',
        position: 'center',
        action: 'wait',
        highlightPadding: 20,
      },
    ],
  },
];
