// Tutorial step definitions for interactive guided tours
// COMPREHENSIVE TUTORIALS - Covering EVERY operation in EVERY module

export interface TutorialStep {
  id: string;
  title: string;
  description: string;
  targetSelector?: string; // CSS selector for element to highlight
  route?: string; // Navigate to this route before showing step
  position?: 'top' | 'bottom' | 'left' | 'right' | 'center';
  action?: 'click' | 'type' | 'scroll' | 'hover' | 'wait';
  actionDelay?: number; // ms to wait before simulating action
  highlightPadding?: number;
  cursorOffset?: { x: number; y: number };
}

export interface Tutorial {
  id: string;
  title: string;
  description: string;
  icon: string;
  estimatedTime: string;
  category: 'principale' | 'commesse' | 'hse' | 'commerciale' | 'amministrazione' | 'logistica' | 'compliance';
  steps: TutorialStep[];
}

export const tutorials: Tutorial[] = [
  // ==================== CATEGORIA: PRINCIPALE ====================
  {
    id: 'dashboard-tour',
    title: 'Tour della Dashboard',
    description: 'Scopri tutte le funzionalità della dashboard principale: statistiche, alert, navigazione',
    icon: 'LayoutDashboard',
    estimatedTime: '3 minuti',
    category: 'principale',
    steps: [
      {
        id: 'intro',
        title: 'Benvenuto nella Dashboard! 👋',
        description: 'La Dashboard è il centro di controllo di Gest-e. Da qui monitora tutto il tuo lavoro in tempo reale.',
        position: 'center',
        route: '/dashboard',
      },
      {
        id: 'stat-cards',
        title: '📊 Statistiche Rapide',
        description: 'Queste card mostrano i numeri chiave: commesse attive, task da completare, alert sicurezza, lavoratori e imprese con documenti critici.',
        targetSelector: '[data-tutorial="stat-cards"]',
        position: 'bottom',
        highlightPadding: 15,
      },
      {
        id: 'sidebar',
        title: '📂 Menu Laterale',
        description: 'Il menu laterale ti dà accesso a tutti i moduli organizzati per reparto. Puoi personalizzare quali voci visualizzare in Impostazioni → Menu.',
        targetSelector: '[data-tutorial="sidebar"]',
        position: 'right',
      },
      {
        id: 'search',
        title: '🔍 Ricerca Globale',
        description: 'Premi Ctrl+K (o ⌘+K su Mac) per aprire la ricerca globale. Cerca cantieri, lavoratori, documenti, task... qualsiasi cosa nel sistema!',
        targetSelector: '[data-tutorial="global-search"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'notifications',
        title: '🔔 Centro Notifiche',
        description: 'L\'icona campanella mostra tutte le notifiche: scadenze imminenti, documenti da rinnovare, task assegnate. Clicca per vedere i dettagli.',
        targetSelector: '[data-tutorial="notifications"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'critical-alerts',
        title: '⚠️ Alert Critici',
        description: 'Quando ci sono scadenze urgenti o documenti scaduti, vedrai un badge rosso con il conteggio. Non ignorarli!',
        targetSelector: '[data-tutorial="critical-alerts"]',
        position: 'bottom',
      },
      {
        id: 'user-menu',
        title: '👤 Menu Utente',
        description: 'Clicca sul tuo nome per accedere al profilo, alle impostazioni o per effettuare il logout.',
        targetSelector: '[data-tutorial="user-menu"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'theme-toggle',
        title: '🌙 Tema Chiaro/Scuro',
        description: 'Puoi passare dal tema scuro a quello chiaro cliccando sull\'icona sole/luna nella barra superiore.',
        targetSelector: '[data-tutorial="theme-toggle"]',
        position: 'bottom',
      },
      {
        id: 'complete',
        title: 'Perfetto! ✨',
        description: 'Ora conosci la Dashboard di Gest-e. Esplora gli altri tutorial per approfondire ogni modulo specifico.',
        position: 'center',
      },
    ],
  },
  {
    id: 'projects-kanban',
    title: 'Gestione Progetti con Kanban',
    description: 'Impara a usare la board Kanban per gestire task e progetti con drag & drop',
    icon: 'FolderKanban',
    estimatedTime: '4 minuti',
    category: 'principale',
    steps: [
      {
        id: 'intro',
        title: 'Progetti & Task 📋',
        description: 'Il modulo Progetti ti permette di gestire tutte le attività con una board Kanban visuale, timeline Gantt e tabelle avanzate.',
        position: 'center',
      },
      {
        id: 'nav-progetti',
        title: 'Accedi ai Progetti',
        description: 'Clicca su "Progetti" nel menu principale per accedere alla gestione task.',
        targetSelector: '[data-tutorial="nav-progetti"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'progetti-page',
        title: 'Pagina Progetti',
        description: 'Qui vedi tutte le task organizzate. Puoi scegliere tra vista Kanban, Tabella o Timeline Gantt.',
        route: '/progetti',
        position: 'center',
      },
      {
        id: 'view-tabs',
        title: '👁️ Scegli la Vista',
        description: 'Usa i tab in alto per passare tra: Kanban (drag & drop), Tabella (filtri avanzati), Timeline (Gantt).',
        targetSelector: '[data-tutorial="view-tabs"]',
        position: 'bottom',
      },
      {
        id: 'kanban-columns',
        title: '📊 Colonne Kanban',
        description: 'Ogni colonna rappresenta uno stato: Da Fare, In Corso, In Revisione, Fatto. Trascina le card tra le colonne!',
        targetSelector: '[data-tutorial="kanban-columns"]',
        position: 'top',
      },
      {
        id: 'new-task',
        title: '➕ Crea Nuova Task',
        description: 'Clicca "Nuova Task" per creare un\'attività. Specifica titolo, descrizione, priorità, scadenza e assegnatario.',
        targetSelector: '[data-tutorial="btn-new-task"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'task-card',
        title: '🎫 Dettaglio Task',
        description: 'Ogni card mostra: priorità (bordo colorato), titolo, scadenza, assegnatario. Clicca per aprire i dettagli completi.',
        targetSelector: '[data-tutorial="task-card"]',
        position: 'right',
        action: 'hover',
      },
      {
        id: 'gantt-view',
        title: '📈 Timeline Gantt',
        description: 'La vista Gantt mostra le task su una timeline temporale. Perfetta per visualizzare sovrapposizioni e dipendenze.',
        targetSelector: '[data-tutorial="gantt-view"]',
        position: 'top',
      },
      {
        id: 'complete',
        title: 'Ottimo! 🎉',
        description: 'Ora sai gestire progetti con Kanban! Usa il drag & drop per spostare le task e mantieni tutto organizzato.',
        position: 'center',
      },
    ],
  },

  // ==================== CATEGORIA: COMMESSE ====================
  {
    id: 'create-commessa',
    title: 'Come Creare una Commessa',
    description: 'Guida completa: creazione anagrafica, dati committente, importo, date, figure responsabili',
    icon: 'Briefcase',
    estimatedTime: '4 minuti',
    category: 'commesse',
    steps: [
      {
        id: 'intro',
        title: 'Benvenuto! 👋',
        description: 'In questo tutorial imparerai come creare una nuova commessa (cantiere) in Gest-e con tutti i dati necessari.',
        position: 'center',
      },
      {
        id: 'nav-cantieri',
        title: 'Naviga verso Commesse',
        description: 'Clicca sulla voce "Commesse" nel menu laterale (sezione Commesse) per accedere alla gestione cantieri.',
        targetSelector: '[data-tutorial="nav-cantieri"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'cantieri-page',
        title: 'Pagina Commesse',
        description: 'Questa è la pagina dove vedi tutte le tue commesse: attive, sospese e concluse. Ogni card mostra stato, importo e progresso.',
        route: '/cantieri',
        position: 'center',
      },
      {
        id: 'filter-status',
        title: '🔍 Filtra per Stato',
        description: 'Usa i filtri in alto per visualizzare solo commesse in un certo stato: Attivo, Sospeso, Completato.',
        targetSelector: '[data-tutorial="filter-status"]',
        position: 'bottom',
      },
      {
        id: 'click-new',
        title: '➕ Crea Nuova Commessa',
        description: 'Clicca sul pulsante "Nuovo Cantiere" per aprire il modulo di creazione.',
        targetSelector: '[data-tutorial="btn-nuovo-cantiere"]',
        position: 'bottom',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'fill-form-intro',
        title: '📝 Compila i Dati',
        description: 'Il form è diviso in sezioni. Compila tutti i campi obbligatori (contrassegnati con *).',
        targetSelector: '[data-tutorial="form-cantiere"]',
        position: 'left',
        highlightPadding: 20,
      },
      {
        id: 'field-nome',
        title: '📌 Nome Commessa',
        description: 'Inserisci un nome descrittivo, es. "Ristrutturazione Villa Rossi" o "Nuovo Capannone Industriale".',
        targetSelector: '[data-tutorial="field-nome"]',
        position: 'right',
        action: 'hover',
      },
      {
        id: 'field-codice',
        title: '🔢 Codice Commessa',
        description: 'Assegna un codice univoco (es. "COM-2025-001"). Questo codice apparirà in tutti i documenti: SAL, rapportini, fatture.',
        targetSelector: '[data-tutorial="field-codice"]',
        position: 'right',
        action: 'hover',
      },
      {
        id: 'field-committente',
        title: '🏢 Committente',
        description: 'Indica il nome del cliente o committente. Questo dato è essenziale per la fatturazione e i documenti ufficiali.',
        targetSelector: '[data-tutorial="field-committente"]',
        position: 'right',
        action: 'hover',
      },
      {
        id: 'field-indirizzo',
        title: '📍 Indirizzo Cantiere',
        description: 'Inserisci l\'indirizzo completo: via, città, provincia, CAP. Utile per DDT, check-in e geolocalizzazione.',
        targetSelector: '[data-tutorial="field-indirizzo"]',
        position: 'right',
        action: 'hover',
      },
      {
        id: 'field-date',
        title: '📅 Date Inizio e Fine',
        description: 'Imposta la data di inizio lavori e la data prevista di fine. Queste date appariranno nel Gantt, calendario e scadenzario.',
        targetSelector: '[data-tutorial="field-date"]',
        position: 'right',
        action: 'hover',
      },
      {
        id: 'field-importo',
        title: '💰 Importo Contratto',
        description: 'Inserisci l\'importo totale del contratto. Questo valore sarà usato per calcolare SAL, avanzamento % e margini.',
        targetSelector: '[data-tutorial="field-importo"]',
        position: 'right',
        action: 'hover',
      },
      {
        id: 'field-responsabile',
        title: '👷 Figure Responsabili',
        description: 'Indica il Direttore Lavori, CSP (Coordinatore Sicurezza Progettazione) e CSE (Coordinatore Sicurezza Esecuzione).',
        targetSelector: '[data-tutorial="field-responsabile"]',
        position: 'right',
        action: 'hover',
      },
      {
        id: 'save-form',
        title: '💾 Salva la Commessa',
        description: 'Quando hai completato tutti i campi, clicca su "Crea Cantiere" per salvare. La commessa apparirà nell\'elenco.',
        targetSelector: '[data-tutorial="btn-salva-cantiere"]',
        position: 'top',
        action: 'hover',
      },
      {
        id: 'complete',
        title: 'Complimenti! 🎉',
        description: 'Hai creato una nuova commessa! Ora puoi assegnare imprese, lavoratori, caricare documenti e monitorare l\'avanzamento.',
        position: 'center',
      },
    ],
  },
  {
    id: 'manage-commessa-detail',
    title: 'Gestire il Dettaglio Commessa',
    description: 'Come navigare nel dettaglio: assegnare imprese, lavoratori, caricare documenti, monitorare SAL',
    icon: 'FileText',
    estimatedTime: '5 minuti',
    category: 'commesse',
    steps: [
      {
        id: 'intro',
        title: 'Dettaglio Commessa 📋',
        description: 'Ogni commessa ha una pagina dettaglio dove gestisci tutte le entità collegate: imprese, lavoratori, documenti, SAL.',
        position: 'center',
      },
      {
        id: 'nav-cantieri',
        title: 'Vai alle Commesse',
        description: 'Accedi alla lista commesse dal menu laterale.',
        targetSelector: '[data-tutorial="nav-cantieri"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1000,
      },
      {
        id: 'select-cantiere',
        title: '👆 Seleziona una Commessa',
        description: 'Clicca su una commessa nell\'elenco per aprire la pagina di dettaglio.',
        route: '/cantieri',
        targetSelector: '[data-tutorial="cantiere-card"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'detail-header',
        title: '📊 Intestazione Commessa',
        description: 'In alto vedi nome, codice, stato e importo. Puoi modificare lo stato (Attivo/Sospeso/Completato) direttamente da qui.',
        targetSelector: '[data-tutorial="detail-header"]',
        position: 'bottom',
      },
      {
        id: 'tabs-navigation',
        title: '📑 Tab di Navigazione',
        description: 'Usa i tab per navigare tra le sezioni: Panoramica, Imprese, Lavoratori, Documenti, SAL, Rapportini.',
        targetSelector: '[data-tutorial="detail-tabs"]',
        position: 'bottom',
      },
      {
        id: 'tab-imprese',
        title: '🏢 Tab Imprese',
        description: 'Qui vedi tutte le imprese assegnate alla commessa. Clicca "Aggiungi Impresa" per assegnarne una nuova.',
        targetSelector: '[data-tutorial="tab-imprese"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'tab-lavoratori',
        title: '👷 Tab Lavoratori',
        description: 'Elenco dei lavoratori attivi sulla commessa. Ogni lavoratore mostra stato documenti (verde/giallo/rosso).',
        targetSelector: '[data-tutorial="tab-lavoratori"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'tab-documenti',
        title: '📄 Tab Documenti',
        description: 'Tutti i documenti della commessa: POS, PSC, autorizzazioni, verbali. Carica nuovi documenti con "Aggiungi Documento".',
        targetSelector: '[data-tutorial="tab-documenti"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'tab-sal',
        title: '📈 Tab SAL',
        description: 'Stato Avanzamento Lavori. Vedi il grafico previsto vs consuntivo e aggiungi nuovi SAL con import Excel.',
        targetSelector: '[data-tutorial="tab-sal"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'complete',
        title: 'Perfetto! ✨',
        description: 'Ora sai navigare nel dettaglio commessa. Ogni tab ti permette di gestire un aspetto specifico del cantiere.',
        position: 'center',
      },
    ],
  },
  {
    id: 'sal-management',
    title: 'Gestione SAL (Avanzamento Lavori)',
    description: 'Come creare SAL, importare da Excel, confrontare budget previsto vs consuntivo',
    icon: 'TrendingUp',
    estimatedTime: '4 minuti',
    category: 'commesse',
    steps: [
      {
        id: 'intro',
        title: 'SAL - Stato Avanzamento Lavori 📈',
        description: 'Il modulo SAL ti permette di tracciare l\'avanzamento economico del cantiere: quanto hai fatturato vs quanto previsto.',
        position: 'center',
      },
      {
        id: 'nav-sal',
        title: 'Accedi al SAL',
        description: 'Vai alla sezione SAL dal menu principale.',
        targetSelector: '[data-tutorial="nav-sal"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'sal-page',
        title: 'Pagina SAL',
        description: 'Qui vedi tutti i SAL registrati, filtrabili per cantiere. Il grafico mostra l\'andamento nel tempo.',
        route: '/sal',
        position: 'center',
      },
      {
        id: 'filter-cantiere',
        title: '🏗️ Filtra per Cantiere',
        description: 'Seleziona un cantiere dal dropdown per vedere solo i suoi SAL e il grafico specifico.',
        targetSelector: '[data-tutorial="filter-cantiere"]',
        position: 'bottom',
      },
      {
        id: 'chart-comparison',
        title: '📊 Grafico Comparativo',
        description: 'Il grafico mostra due linee: Previsto (budget) e Consuntivo (fatturato). Confronta per individuare scostamenti.',
        targetSelector: '[data-tutorial="sal-chart"]',
        position: 'top',
      },
      {
        id: 'new-sal',
        title: '➕ Nuovo SAL',
        description: 'Clicca "Nuovo SAL" per registrare un nuovo stato avanzamento. Inserisci numero, data, importo e note.',
        targetSelector: '[data-tutorial="btn-new-sal"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'import-excel',
        title: '📥 Import da Excel',
        description: 'Puoi importare SAL massivamente da file Excel. Clicca "Importa" e carica il file con le colonne richieste.',
        targetSelector: '[data-tutorial="btn-import-sal"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'export-report',
        title: '📤 Esporta Report',
        description: 'Genera un report PDF/Excel con tutti i SAL da inviare al Direttore Lavori o al committente.',
        targetSelector: '[data-tutorial="btn-export-sal"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'complete',
        title: 'Ottimo! 🎉',
        description: 'Ora sai gestire i SAL! Monitora regolarmente per tenere sotto controllo la marginalità del cantiere.',
        position: 'center',
      },
    ],
  },

  // ==================== CATEGORIA: HSE & SICUREZZA ====================
  {
    id: 'hse-overview',
    title: 'Panoramica HSE & Sicurezza',
    description: 'Cruscotto sicurezza: alert documenti scaduti, formazioni, visite mediche, compliance D.Lgs 81/08',
    icon: 'ShieldCheck',
    estimatedTime: '5 minuti',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Modulo HSE 🛡️',
        description: 'Il modulo HSE ti permette di gestire tutti gli aspetti della sicurezza sul lavoro secondo il D.Lgs 81/08. Alert automatici, scadenze, documenti.',
        position: 'center',
      },
      {
        id: 'nav-hse',
        title: 'Accedi alla Dashboard HSE',
        description: 'Clicca su "HSE Dashboard" nel menu Sicurezza & HSE.',
        targetSelector: '[data-tutorial="nav-hse"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'hse-dashboard',
        title: 'Dashboard HSE',
        description: 'Il cruscotto mostra a colpo d\'occhio: documenti scaduti (rosso), in scadenza (giallo), validi (verde).',
        route: '/hse',
        position: 'center',
      },
      {
        id: 'alert-cards',
        title: '🚨 Card Alert',
        description: 'Ogni card mostra un conteggio: Documenti Scaduti, Formazioni Scadute, Visite Mediche Scadute, Lavoratori Critici.',
        targetSelector: '[data-tutorial="hse-alert-cards"]',
        position: 'bottom',
      },
      {
        id: 'semaforo-system',
        title: '🚦 Sistema a Semaforo',
        description: 'Ogni entità (lavoratore, impresa) ha un semaforo: Verde = tutto OK, Giallo = scadenza entro 30gg, Rosso = scaduto.',
        targetSelector: '[data-tutorial="hse-semaforo"]',
        position: 'right',
      },
      {
        id: 'filter-critical',
        title: '🔴 Filtra Critici',
        description: 'Usa i filtri per vedere solo elementi critici. Risolvili prioritariamente per mantenere la compliance.',
        targetSelector: '[data-tutorial="hse-filter-critical"]',
        position: 'bottom',
      },
      {
        id: 'nav-formazione',
        title: 'Gestione Formazione',
        description: 'Dalla sezione Formazione gestisci tutti i corsi di sicurezza: Art. 37, Primo Soccorso, Antincendio, ecc.',
        targetSelector: '[data-tutorial="nav-formazione"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'formazione-page',
        title: 'Elenco Formazioni',
        description: 'Ogni riga mostra: lavoratore, corso, data conseguimento, scadenza, stato. I colori indicano urgenza.',
        route: '/formazione',
        position: 'center',
      },
      {
        id: 'nav-dpi',
        title: 'Gestione DPI',
        description: 'Nella sezione DPI tracci la consegna dei dispositivi di protezione individuale a ogni lavoratore.',
        targetSelector: '[data-tutorial="nav-dpi"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'dpi-page',
        title: 'Registro DPI',
        description: 'Registra consegna di elmetti, guanti, scarpe, imbracature. Traccia data, taglia, firma del lavoratore.',
        route: '/dpi',
        position: 'center',
      },
      {
        id: 'nav-sorveglianza',
        title: 'Sorveglianza Sanitaria',
        description: 'La sezione Visite Mediche gestisce idoneità, limitazioni, scadenze del medico competente.',
        targetSelector: '[data-tutorial="nav-sorveglianza"]',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'complete',
        title: 'Ottimo lavoro! 🎉',
        description: 'Conosci le basi del modulo HSE. Esplora anche Check-in Sicurezza e D.Lgs 81/08 per una gestione completa della sicurezza.',
        position: 'center',
      },
    ],
  },
  {
    id: 'formazione-management',
    title: 'Gestione Formazione Lavoratori',
    description: 'Come registrare corsi, caricare attestati, monitorare scadenze, pianificare rinnovi',
    icon: 'GraduationCap',
    estimatedTime: '4 minuti',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Formazione Sicurezza 🎓',
        description: 'La formazione è obbligatoria per legge (D.Lgs 81/08 Art. 37). Questo modulo ti aiuta a tracciare tutti i corsi e le scadenze.',
        position: 'center',
      },
      {
        id: 'nav-formazione',
        title: 'Accedi a Formazione',
        description: 'Vai alla sezione Formazione dal menu Sicurezza & HSE.',
        targetSelector: '[data-tutorial="nav-formazione"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'formazione-list',
        title: 'Elenco Formazioni',
        description: 'La tabella mostra tutte le formazioni registrate. Ogni riga: lavoratore, tipo corso, data, scadenza, stato.',
        route: '/formazione',
        position: 'center',
      },
      {
        id: 'filter-lavoratore',
        title: '👷 Filtra per Lavoratore',
        description: 'Cerca un lavoratore specifico per vedere tutti i suoi corsi e verificare la compliance.',
        targetSelector: '[data-tutorial="filter-lavoratore"]',
        position: 'bottom',
      },
      {
        id: 'filter-tipo',
        title: '📚 Filtra per Tipo Corso',
        description: 'Filtra per tipo: Art. 37 Base, Primo Soccorso, Antincendio, Ponteggi, PLE, ecc.',
        targetSelector: '[data-tutorial="filter-tipo"]',
        position: 'bottom',
      },
      {
        id: 'new-formazione',
        title: '➕ Nuova Formazione',
        description: 'Clicca "Nuova Formazione" per registrare un corso completato.',
        targetSelector: '[data-tutorial="btn-new-formazione"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'form-fields',
        title: '📝 Campi Formazione',
        description: 'Compila: Lavoratore, Tipo Corso, Titolo, Data Conseguimento, Ente Formatore, Ore, Data Scadenza.',
        targetSelector: '[data-tutorial="form-formazione"]',
        position: 'left',
        highlightPadding: 15,
      },
      {
        id: 'upload-attestato',
        title: '📎 Carica Attestato',
        description: 'Carica il PDF o immagine dell\'attestato. Sarà allegato alla formazione e scaricabile in qualsiasi momento.',
        targetSelector: '[data-tutorial="upload-attestato"]',
        position: 'right',
        action: 'hover',
      },
      {
        id: 'scadenza-auto',
        title: '⏰ Scadenza Automatica',
        description: 'Il sistema calcola automaticamente quando la formazione scade. Riceverai alert 30 giorni prima.',
        targetSelector: '[data-tutorial="scadenza-info"]',
        position: 'top',
      },
      {
        id: 'complete',
        title: 'Perfetto! ✨',
        description: 'Ora sai gestire le formazioni! Tieni sempre aggiornati gli attestati per evitare sanzioni durante le ispezioni.',
        position: 'center',
      },
    ],
  },
  {
    id: 'dpi-consegna',
    title: 'Consegna e Tracciamento DPI',
    description: 'Registrare consegna DPI, gestire taglie, scadenze, storico per lavoratore',
    icon: 'HardHat',
    estimatedTime: '3 minuti',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'DPI - Dispositivi di Protezione 🦺',
        description: 'La consegna dei DPI deve essere documentata (Art. 77 D.Lgs 81/08). Questo modulo traccia ogni consegna.',
        position: 'center',
      },
      {
        id: 'nav-dpi',
        title: 'Vai a DPI',
        description: 'Accedi alla sezione DPI dal menu Sicurezza & HSE.',
        targetSelector: '[data-tutorial="nav-dpi"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'dpi-list',
        title: 'Registro Consegne DPI',
        description: 'La tabella mostra tutte le consegne: lavoratore, tipo DPI, data consegna, taglia, scadenza.',
        route: '/dpi',
        position: 'center',
      },
      {
        id: 'categories',
        title: '🏷️ Categorie DPI',
        description: 'I DPI sono organizzati per categoria: Testa (elmetti), Mani (guanti), Piedi (scarpe), Corpo (tute), Caduta (imbracature).',
        targetSelector: '[data-tutorial="dpi-categories"]',
        position: 'bottom',
      },
      {
        id: 'new-dpi',
        title: '➕ Nuova Consegna',
        description: 'Clicca "Nuova Consegna" per registrare la consegna di un DPI a un lavoratore.',
        targetSelector: '[data-tutorial="btn-new-dpi"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'form-dpi',
        title: '📝 Dati Consegna',
        description: 'Seleziona: Lavoratore, Tipo DPI, Marca/Modello, Taglia, Quantità, Data Consegna, Eventuale Scadenza.',
        targetSelector: '[data-tutorial="form-dpi"]',
        position: 'left',
        highlightPadding: 15,
      },
      {
        id: 'storico',
        title: '📜 Storico Lavoratore',
        description: 'Per ogni lavoratore puoi vedere lo storico completo di tutte le consegne DPI ricevute nel tempo.',
        targetSelector: '[data-tutorial="dpi-storico"]',
        position: 'right',
      },
      {
        id: 'complete',
        title: 'Ottimo! 🎉',
        description: 'Ora sai registrare le consegne DPI! Stampa le schede per farle firmare ai lavoratori.',
        position: 'center',
      },
    ],
  },
  {
    id: 'sorveglianza-sanitaria',
    title: 'Sorveglianza Sanitaria e Visite Mediche',
    description: 'Programmare visite, registrare esiti, gestire idoneità e limitazioni, scadenzario',
    icon: 'Stethoscope',
    estimatedTime: '4 minuti',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Sorveglianza Sanitaria 🏥',
        description: 'La sorveglianza sanitaria è obbligatoria (Art. 41 D.Lgs 81/08). Gestisci visite, idoneità e protocollo sanitario.',
        position: 'center',
      },
      {
        id: 'nav-sorveglianza',
        title: 'Accedi a Sorveglianza',
        description: 'Vai alla sezione Sorveglianza Sanitaria dal menu HSE.',
        targetSelector: '[data-tutorial="nav-sorveglianza"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'visite-list',
        title: 'Elenco Visite Mediche',
        description: 'Visualizza tutte le visite: lavoratore, tipo visita, data, esito, prossima scadenza.',
        route: '/sorveglianza-sanitaria',
        position: 'center',
      },
      {
        id: 'calendar-visite',
        title: '📅 Calendario Visite',
        description: 'Il calendario mostra le visite programmate. Pianifica in anticipo per evitare lavoratori non idonei.',
        targetSelector: '[data-tutorial="calendar-visite"]',
        position: 'top',
      },
      {
        id: 'new-visita',
        title: '➕ Nuova Visita',
        description: 'Registra una nuova visita medica: lavoratore, tipo (preventiva, periodica, cambio mansione), data.',
        targetSelector: '[data-tutorial="btn-new-visita"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'esito-idoneita',
        title: '✅ Esito e Idoneità',
        description: 'Registra l\'esito: Idoneo, Idoneo con Limitazioni, Non Idoneo Temporaneo, Non Idoneo Permanente.',
        targetSelector: '[data-tutorial="esito-idoneita"]',
        position: 'right',
      },
      {
        id: 'limitazioni',
        title: '⚠️ Limitazioni',
        description: 'Se ci sono limitazioni (es. "no lavori in quota", "no movimentazione carichi"), annotale qui.',
        targetSelector: '[data-tutorial="limitazioni"]',
        position: 'right',
      },
      {
        id: 'scadenze-auto',
        title: '⏰ Scadenze Automatiche',
        description: 'Il sistema calcola la prossima visita in base alla periodicità del protocollo sanitario aziendale.',
        targetSelector: '[data-tutorial="scadenze-visite"]',
        position: 'top',
      },
      {
        id: 'complete',
        title: 'Perfetto! ✨',
        description: 'Ora gestisci la sorveglianza sanitaria! Riceverai alert automatici prima delle scadenze.',
        position: 'center',
      },
    ],
  },
  {
    id: 'checkin-sicurezza',
    title: 'Check-in Sicurezza Giornaliero',
    description: 'Verifica pre-lavoro: DPI, condizioni meteo, briefing, segnalazioni pericoli',
    icon: 'ClipboardCheck',
    estimatedTime: '3 minuti',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Check-in Sicurezza ✅',
        description: 'Il check-in giornaliero documenta le verifiche pre-lavoro: DPI, condizioni, briefing. Fondamentale in caso di ispezioni.',
        position: 'center',
      },
      {
        id: 'nav-checkin',
        title: 'Accedi a Check-in',
        description: 'Vai alla sezione Check-in Sicurezza dal menu HSE.',
        targetSelector: '[data-tutorial="nav-checkin"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'checkin-list',
        title: 'Storico Check-in',
        description: 'Vedi tutti i check-in effettuati: cantiere, data, ora, responsabile, esito verifiche.',
        route: '/checkin-sicurezza',
        position: 'center',
      },
      {
        id: 'new-checkin',
        title: '➕ Nuovo Check-in',
        description: 'Clicca "Nuovo Check-in" per iniziare la verifica giornaliera di un cantiere.',
        targetSelector: '[data-tutorial="btn-new-checkin"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'select-cantiere',
        title: '🏗️ Seleziona Cantiere',
        description: 'Scegli il cantiere su cui stai effettuando il check-in.',
        targetSelector: '[data-tutorial="checkin-cantiere"]',
        position: 'right',
      },
      {
        id: 'checklist-dpi',
        title: '🦺 Verifica DPI',
        description: 'Spunta: tutti i lavoratori hanno i DPI corretti? Se mancano, indica quali.',
        targetSelector: '[data-tutorial="checklist-dpi"]',
        position: 'right',
      },
      {
        id: 'checklist-meteo',
        title: '🌤️ Condizioni Meteo',
        description: 'Le condizioni meteo permettono di lavorare in sicurezza? In caso di vento forte o temporale, segnala.',
        targetSelector: '[data-tutorial="checklist-meteo"]',
        position: 'right',
      },
      {
        id: 'briefing',
        title: '📢 Briefing Effettuato',
        description: 'Hai fatto il briefing ai lavoratori sulle attività della giornata? Indica gli argomenti trattati.',
        targetSelector: '[data-tutorial="checklist-briefing"]',
        position: 'right',
      },
      {
        id: 'segnalazioni',
        title: '⚠️ Segnalazioni Pericoli',
        description: 'Se noti situazioni pericolose, descrivile qui. Puoi allegare foto.',
        targetSelector: '[data-tutorial="segnalazioni"]',
        position: 'right',
      },
      {
        id: 'firma',
        title: '✍️ Firma Responsabile',
        description: 'Firma digitalmente il check-in. La firma conferma che le verifiche sono state effettuate.',
        targetSelector: '[data-tutorial="firma-checkin"]',
        position: 'top',
      },
      {
        id: 'complete',
        title: 'Ottimo! 🎉',
        description: 'Hai completato un check-in! Fai check-in ogni mattina per documentare la sicurezza del cantiere.',
        position: 'center',
      },
    ],
  },
  {
    id: 'imprese-esterne',
    title: 'Gestione Imprese Esterne (Subappaltatori)',
    description: 'Anagrafica imprese, documenti obbligatori (DURC, Visura), assegnazione a cantieri',
    icon: 'Building2',
    estimatedTime: '4 minuti',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Imprese Esterne 🏢',
        description: 'Gestisci i subappaltatori con tutti i documenti obbligatori: DURC, Visura Camerale, Polizza RC, SOA.',
        position: 'center',
      },
      {
        id: 'nav-imprese',
        title: 'Vai a Imprese',
        description: 'Accedi alla sezione Imprese dal menu Sicurezza & HSE.',
        targetSelector: '[data-tutorial="nav-imprese"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'imprese-list',
        title: 'Elenco Imprese',
        description: 'Ogni card mostra: ragione sociale, P.IVA, rating, stato documenti (semaforo verde/giallo/rosso).',
        route: '/imprese',
        position: 'center',
      },
      {
        id: 'filter-status',
        title: '🚦 Filtra per Stato',
        description: 'Filtra per stato documenti: Tutte, Solo Critiche (rosso), In Scadenza (giallo), Regolari (verde).',
        targetSelector: '[data-tutorial="filter-imprese"]',
        position: 'bottom',
      },
      {
        id: 'new-impresa',
        title: '➕ Nuova Impresa',
        description: 'Clicca "Nuova Impresa" per aggiungere un subappaltatore.',
        targetSelector: '[data-tutorial="btn-new-impresa"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'form-anagrafica',
        title: '📝 Anagrafica',
        description: 'Compila: Ragione Sociale, P.IVA, CF, Indirizzo, PEC, Categoria SOA, Rating.',
        targetSelector: '[data-tutorial="form-impresa"]',
        position: 'left',
        highlightPadding: 15,
      },
      {
        id: 'documenti-impresa',
        title: '📄 Documenti Obbligatori',
        description: 'Per ogni impresa carica: DURC, Visura Camerale, Polizza RC, Attestazione SOA, DUVRI.',
        targetSelector: '[data-tutorial="docs-impresa"]',
        position: 'right',
      },
      {
        id: 'scadenze-docs',
        title: '⏰ Scadenze Documenti',
        description: 'Ogni documento ha una scadenza. Il sistema ti avvisa automaticamente prima della scadenza.',
        targetSelector: '[data-tutorial="scadenze-impresa"]',
        position: 'top',
      },
      {
        id: 'assegna-cantiere',
        title: '🏗️ Assegna a Cantiere',
        description: 'Dal dettaglio impresa puoi vedere in quali cantieri è assegnata e aggiungerne di nuovi.',
        targetSelector: '[data-tutorial="assegna-cantiere"]',
        position: 'right',
      },
      {
        id: 'complete',
        title: 'Perfetto! ✨',
        description: 'Ora gestisci le imprese esterne! Tieni sempre i documenti aggiornati per evitare problemi durante le ispezioni.',
        position: 'center',
      },
    ],
  },
  {
    id: 'lavoratori-management',
    title: 'Anagrafica e Gestione Lavoratori',
    description: 'Creare schede lavoratore, assegnare a imprese/cantieri, gestire documenti personali',
    icon: 'Users',
    estimatedTime: '4 minuti',
    category: 'hse',
    steps: [
      {
        id: 'intro',
        title: 'Gestione Lavoratori 👷',
        description: 'Ogni lavoratore ha una scheda completa: dati anagrafici, formazioni, DPI, visite mediche, cantieri assegnati.',
        position: 'center',
      },
      {
        id: 'nav-lavoratori',
        title: 'Vai a Lavoratori',
        description: 'Accedi alla sezione Lavoratori dal menu HSE.',
        targetSelector: '[data-tutorial="nav-lavoratori"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'lavoratori-list',
        title: 'Elenco Lavoratori',
        description: 'Ogni card mostra: nome, cognome, mansione, impresa, stato documenti (semaforo).',
        route: '/lavoratori',
        position: 'center',
      },
      {
        id: 'search-lavoratore',
        title: '🔍 Cerca Lavoratore',
        description: 'Usa la barra di ricerca per trovare rapidamente un lavoratore per nome o codice fiscale.',
        targetSelector: '[data-tutorial="search-lavoratori"]',
        position: 'bottom',
      },
      {
        id: 'new-lavoratore',
        title: '➕ Nuovo Lavoratore',
        description: 'Clicca "Nuovo Lavoratore" per aggiungere un dipendente o lavoratore esterno.',
        targetSelector: '[data-tutorial="btn-new-lavoratore"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'form-lavoratore',
        title: '📝 Dati Anagrafici',
        description: 'Compila: Nome, Cognome, CF, Data/Luogo Nascita, Indirizzo, Telefono, Email, Mansione, Livello.',
        targetSelector: '[data-tutorial="form-lavoratore"]',
        position: 'left',
        highlightPadding: 15,
      },
      {
        id: 'assegna-impresa',
        title: '🏢 Assegna a Impresa',
        description: 'Seleziona l\'impresa di appartenenza. Per dipendenti diretti, seleziona la tua azienda.',
        targetSelector: '[data-tutorial="impresa-lavoratore"]',
        position: 'right',
      },
      {
        id: 'dettaglio-lavoratore',
        title: '📋 Scheda Completa',
        description: 'Dalla scheda lavoratore vedi: formazioni, DPI consegnati, visite mediche, cantieri assegnati.',
        targetSelector: '[data-tutorial="dettaglio-lavoratore"]',
        position: 'right',
      },
      {
        id: 'stato-compliance',
        title: '🚦 Stato Compliance',
        description: 'Il semaforo sintetizza lo stato: Verde = tutto OK, Giallo = qualcosa in scadenza, Rosso = documenti scaduti.',
        targetSelector: '[data-tutorial="stato-lavoratore"]',
        position: 'top',
      },
      {
        id: 'complete',
        title: 'Ottimo! 🎉',
        description: 'Ora gestisci i lavoratori! Ogni lavoratore deve avere formazioni, DPI e visite mediche in regola.',
        position: 'center',
      },
    ],
  },

  // ==================== CATEGORIA: COMMERCIALE ====================
  {
    id: 'crm-leads',
    title: 'CRM: Gestione Lead e Opportunità',
    description: 'Pipeline commerciale: acquisire lead, gestire opportunità, convertire in preventivi',
    icon: 'Users',
    estimatedTime: '4 minuti',
    category: 'commerciale',
    steps: [
      {
        id: 'intro',
        title: 'CRM Commerciale 💼',
        description: 'Il modulo CRM ti permette di gestire l\'intero ciclo di acquisizione clienti: dal primo contatto alla commessa.',
        position: 'center',
      },
      {
        id: 'nav-commerciale',
        title: 'Vai all\'Ufficio Commerciale',
        description: 'Accedi alla sezione Ufficio Commerciale dal menu.',
        targetSelector: '[data-tutorial="nav-commerciale"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'commerciale-page',
        title: 'Dashboard Commerciale',
        description: 'Vedi le statistiche: lead in corso, valore pipeline, preventivi in attesa, tasso conversione.',
        route: '/ufficio-commerciale',
        position: 'center',
      },
      {
        id: 'tab-leads',
        title: '👥 Tab Lead',
        description: 'I Lead sono i potenziali clienti non ancora qualificati. Gestisci nome, azienda, fonte, note.',
        targetSelector: '[data-tutorial="tab-leads"]',
        position: 'bottom',
      },
      {
        id: 'new-lead',
        title: '➕ Nuovo Lead',
        description: 'Clicca "Nuovo Lead" quando ricevi un contatto interessato (telefono, email, passaparola).',
        targetSelector: '[data-tutorial="btn-new-lead"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'lead-stages',
        title: '📊 Stati Lead',
        description: 'Un lead passa attraverso: Nuovo → Contattato → Qualificato → Proposta → Negoziazione → Vinto/Perso.',
        targetSelector: '[data-tutorial="lead-stages"]',
        position: 'right',
      },
      {
        id: 'lead-details',
        title: '📝 Dettagli Lead',
        description: 'Per ogni lead registra: valore stimato, probabilità, prossimo contatto, note delle chiamate.',
        targetSelector: '[data-tutorial="lead-details"]',
        position: 'left',
      },
      {
        id: 'convert-preventivo',
        title: '📄 Crea Preventivo',
        description: 'Quando il lead è qualificato, clicca "Crea Preventivo" per generare un\'offerta formale.',
        targetSelector: '[data-tutorial="btn-preventivo"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'complete',
        title: 'Perfetto! ✨',
        description: 'Ora gestisci la pipeline commerciale! Tieni aggiornati i lead per migliorare il tasso di conversione.',
        position: 'center',
      },
    ],
  },
  {
    id: 'preventivi-creation',
    title: 'Creazione Preventivi',
    description: 'Come creare preventivi dettagliati con righe prodotto, sconti, validità',
    icon: 'FileText',
    estimatedTime: '4 minuti',
    category: 'commerciale',
    steps: [
      {
        id: 'intro',
        title: 'Preventivi 📄',
        description: 'Crea preventivi professionali con intestazione aziendale, righe dettagliate, sconti e condizioni.',
        position: 'center',
      },
      {
        id: 'nav-preventivi',
        title: 'Vai ai Preventivi',
        description: 'Dalla sezione Ufficio Commerciale, seleziona il tab Preventivi.',
        route: '/ufficio-commerciale',
        targetSelector: '[data-tutorial="tab-preventivi"]',
        position: 'bottom',
        action: 'click',
        actionDelay: 1000,
      },
      {
        id: 'preventivi-list',
        title: 'Elenco Preventivi',
        description: 'Vedi tutti i preventivi: numero, cliente, importo, stato (Bozza, Inviato, Accettato, Rifiutato).',
        targetSelector: '[data-tutorial="preventivi-list"]',
        position: 'center',
      },
      {
        id: 'new-preventivo',
        title: '➕ Nuovo Preventivo',
        description: 'Clicca "Nuovo Preventivo" per creare un\'offerta.',
        targetSelector: '[data-tutorial="btn-new-preventivo"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'cliente-select',
        title: '👤 Seleziona Cliente',
        description: 'Scegli il cliente dalla rubrica o inserisci i dati manualmente. I dati fiscali saranno usati nella stampa.',
        targetSelector: '[data-tutorial="cliente-preventivo"]',
        position: 'right',
      },
      {
        id: 'oggetto',
        title: '📌 Oggetto',
        description: 'Descrivi brevemente l\'oggetto del preventivo, es. "Ristrutturazione bagno piano terra".',
        targetSelector: '[data-tutorial="oggetto-preventivo"]',
        position: 'right',
      },
      {
        id: 'righe',
        title: '📋 Righe Preventivo',
        description: 'Aggiungi le voci: descrizione lavorazione, quantità, unità di misura, prezzo unitario, IVA.',
        targetSelector: '[data-tutorial="righe-preventivo"]',
        position: 'left',
        highlightPadding: 15,
      },
      {
        id: 'sconto',
        title: '💰 Sconto',
        description: 'Applica uno sconto percentuale globale se necessario.',
        targetSelector: '[data-tutorial="sconto-preventivo"]',
        position: 'right',
      },
      {
        id: 'validita',
        title: '📅 Validità',
        description: 'Imposta la validità del preventivo in giorni (es. 30 giorni). Dopo scade e andrà rinnovato.',
        targetSelector: '[data-tutorial="validita-preventivo"]',
        position: 'right',
      },
      {
        id: 'export-pdf',
        title: '📥 Esporta PDF',
        description: 'Genera il PDF professionale con logo aziendale, pronto per essere inviato al cliente.',
        targetSelector: '[data-tutorial="export-preventivo"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'complete',
        title: 'Ottimo! 🎉',
        description: 'Hai creato un preventivo! Quando viene accettato, puoi convertirlo in commessa con un click.',
        position: 'center',
      },
    ],
  },

  // ==================== CATEGORIA: AMMINISTRAZIONE ====================
  {
    id: 'computo-metrico',
    title: 'Computo Metrico Estimativo',
    description: 'Creare computi, strutturare categorie, inserire voci, calcolare totali, export',
    icon: 'Calculator',
    estimatedTime: '5 minuti',
    category: 'amministrazione',
    steps: [
      {
        id: 'intro',
        title: 'Computo Metrico 🧮',
        description: 'Il computo metrico estimativo calcola il costo delle lavorazioni. Compatibile con format Primus e Excel.',
        position: 'center',
      },
      {
        id: 'nav-computo',
        title: 'Vai a Computo Metrico',
        description: 'Accedi alla sezione Computo Metrico dal menu Amministrazione.',
        targetSelector: '[data-tutorial="nav-computo"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'computo-list',
        title: 'Elenco Computi',
        description: 'Vedi tutti i computi creati: nome, cantiere associato, totale, stato (Bozza, Approvato).',
        route: '/computo-metrico',
        position: 'center',
      },
      {
        id: 'new-computo',
        title: '➕ Nuovo Computo',
        description: 'Clicca "Nuovo Computo" per iniziare a creare un computo metrico.',
        targetSelector: '[data-tutorial="btn-new-computo"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'nome-computo',
        title: '📌 Nome e Cantiere',
        description: 'Assegna un nome al computo e collegalo a un cantiere per la contabilità lavori.',
        targetSelector: '[data-tutorial="nome-computo"]',
        position: 'right',
      },
      {
        id: 'categorie',
        title: '📂 Categorie Lavori',
        description: 'Organizza le lavorazioni in categorie: Opere Edili, Impianti Elettrici, Impianti Idraulici, ecc.',
        targetSelector: '[data-tutorial="categorie-computo"]',
        position: 'left',
      },
      {
        id: 'add-voce',
        title: '➕ Aggiungi Voce',
        description: 'Per ogni categoria, aggiungi le voci: descrizione lavorazione, unità di misura, quantità, prezzo unitario.',
        targetSelector: '[data-tutorial="btn-add-voce"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'listino',
        title: '📋 Usa Listino',
        description: 'Puoi importare voci dal listino prezzi aziendale o da prezzari regionali (DEI, Regione).',
        targetSelector: '[data-tutorial="import-listino"]',
        position: 'right',
      },
      {
        id: 'calcolo-auto',
        title: '🔢 Calcolo Automatico',
        description: 'Il sistema calcola automaticamente: importo per voce = quantità × prezzo unitario. I totali si aggiornano in tempo reale.',
        targetSelector: '[data-tutorial="totale-computo"]',
        position: 'top',
      },
      {
        id: 'ai-assist',
        title: '🤖 Assistente AI',
        description: 'Usa l\'assistente AI per generare automaticamente voci a partire da una descrizione testuale dei lavori.',
        targetSelector: '[data-tutorial="ai-computo"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'export',
        title: '📤 Export',
        description: 'Esporta in Excel o PDF. Il formato è compatibile con Primus e altri software di computo.',
        targetSelector: '[data-tutorial="export-computo"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'complete',
        title: 'Perfetto! ✨',
        description: 'Hai creato un computo metrico! Usalo per preventivi, SAL e contabilità lavori.',
        position: 'center',
      },
    ],
  },
  {
    id: 'fatturazione',
    title: 'Gestione Fatture Attive e Passive',
    description: 'Emettere fatture, registrare fatture fornitori, gestire scadenze pagamenti',
    icon: 'Euro',
    estimatedTime: '4 minuti',
    category: 'amministrazione',
    steps: [
      {
        id: 'intro',
        title: 'Fatturazione 📑',
        description: 'Gestisci il ciclo attivo (fatture ai clienti) e passivo (fatture da fornitori). Traccia scadenze e pagamenti.',
        position: 'center',
      },
      {
        id: 'nav-amministrazione',
        title: 'Vai ad Amministrazione',
        description: 'Accedi al Reparto Amministrazione dal menu.',
        targetSelector: '[data-tutorial="nav-amministrazione"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'fatture-tab',
        title: '📄 Tab Fatture',
        description: 'Nella sezione Fatture vedi entrambi i cicli: Attive (emesse) e Passive (ricevute).',
        route: '/reparto-amministrazione',
        targetSelector: '[data-tutorial="tab-fatture"]',
        position: 'bottom',
      },
      {
        id: 'fatture-list',
        title: 'Elenco Fatture',
        description: 'Ogni riga mostra: numero, data, cliente/fornitore, imponibile, IVA, totale, stato (Pagata, In Attesa, Scaduta).',
        targetSelector: '[data-tutorial="fatture-list"]',
        position: 'center',
      },
      {
        id: 'new-fattura',
        title: '➕ Nuova Fattura',
        description: 'Clicca "Nuova Fattura Attiva" per emettere una fattura a un cliente.',
        targetSelector: '[data-tutorial="btn-new-fattura"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'dati-fattura',
        title: '📝 Dati Fattura',
        description: 'Compila: cliente, numero, data, scadenza, descrizione, imponibile, aliquota IVA.',
        targetSelector: '[data-tutorial="form-fattura"]',
        position: 'left',
        highlightPadding: 15,
      },
      {
        id: 'collegamento-commessa',
        title: '🏗️ Collega a Commessa',
        description: 'Collega la fattura a una commessa per avere la contabilità separata per cantiere.',
        targetSelector: '[data-tutorial="commessa-fattura"]',
        position: 'right',
      },
      {
        id: 'registra-pagamento',
        title: '✅ Registra Pagamento',
        description: 'Quando ricevi il pagamento, clicca su "Registra Pagamento" e inserisci data e metodo.',
        targetSelector: '[data-tutorial="btn-pagamento"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'scadenze',
        title: '⏰ Scadenze',
        description: 'Il sistema mostra le fatture in scadenza e quelle scadute. Ricevi alert automatici.',
        targetSelector: '[data-tutorial="scadenze-fatture"]',
        position: 'top',
      },
      {
        id: 'complete',
        title: 'Ottimo! 🎉',
        description: 'Ora gestisci le fatture! Tieni monitorato il cash flow con le statistiche di incasso.',
        position: 'center',
      },
    ],
  },
  {
    id: 'rapportini-giornalieri',
    title: 'Rapportini Giornalieri di Cantiere',
    description: 'Registrare presenze, lavorazioni eseguite, materiali, meteo, foto',
    icon: 'FileText',
    estimatedTime: '4 minuti',
    category: 'amministrazione',
    steps: [
      {
        id: 'intro',
        title: 'Rapportini di Cantiere 📝',
        description: 'Il rapportino documenta ogni giorno: chi era presente, cosa è stato fatto, materiali usati, condizioni.',
        position: 'center',
      },
      {
        id: 'nav-rapportini',
        title: 'Vai a Rapportini',
        description: 'Accedi alla sezione Rapportini dal menu.',
        targetSelector: '[data-tutorial="nav-rapportini"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'rapportini-list',
        title: 'Elenco Rapportini',
        description: 'Vedi tutti i rapportini: data, cantiere, numero lavoratori, ore totali, stato.',
        route: '/rapportini',
        position: 'center',
      },
      {
        id: 'filter-cantiere',
        title: '🏗️ Filtra per Cantiere',
        description: 'Seleziona un cantiere per vedere solo i suoi rapportini.',
        targetSelector: '[data-tutorial="filter-rapportini"]',
        position: 'bottom',
      },
      {
        id: 'new-rapportino',
        title: '➕ Nuovo Rapportino',
        description: 'Clicca "Nuovo Rapportino" per creare il report giornaliero.',
        targetSelector: '[data-tutorial="btn-new-rapportino"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'select-cantiere',
        title: '🏗️ Seleziona Cantiere',
        description: 'Scegli il cantiere e la data del rapportino.',
        targetSelector: '[data-tutorial="cantiere-rapportino"]',
        position: 'right',
      },
      {
        id: 'presenze',
        title: '👷 Presenze',
        description: 'Aggiungi i lavoratori presenti con ore ordinarie e straordinarie.',
        targetSelector: '[data-tutorial="presenze-rapportino"]',
        position: 'left',
        highlightPadding: 15,
      },
      {
        id: 'lavorazioni',
        title: '🔨 Lavorazioni Eseguite',
        description: 'Descrivi le attività svolte nella giornata. Sii dettagliato per la contabilità lavori.',
        targetSelector: '[data-tutorial="lavorazioni-rapportino"]',
        position: 'right',
      },
      {
        id: 'materiali',
        title: '📦 Materiali Utilizzati',
        description: 'Elenca i materiali prelevati dal magazzino o ricevuti in cantiere.',
        targetSelector: '[data-tutorial="materiali-rapportino"]',
        position: 'right',
      },
      {
        id: 'meteo-foto',
        title: '🌤️ Meteo e Foto',
        description: 'Indica le condizioni meteo e allega foto del progresso lavori.',
        targetSelector: '[data-tutorial="meteo-rapportino"]',
        position: 'right',
      },
      {
        id: 'export',
        title: '📤 Esporta',
        description: 'Esporta il rapportino in PDF per archivio o per il DL.',
        targetSelector: '[data-tutorial="export-rapportino"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'complete',
        title: 'Perfetto! ✨',
        description: 'Hai creato un rapportino! Compila un rapportino ogni giorno per avere documentazione completa.',
        position: 'center',
      },
    ],
  },

  // ==================== CATEGORIA: LOGISTICA ====================
  {
    id: 'risorse-mezzi',
    title: 'Gestione Risorse e Mezzi',
    description: 'Anagrafica mezzi, manutenzioni programmate, prenotazioni, tracking km e carburante',
    icon: 'Truck',
    estimatedTime: '4 minuti',
    category: 'logistica',
    steps: [
      {
        id: 'intro',
        title: 'Risorse e Mezzi 🚜',
        description: 'Gestisci la flotta aziendale: veicoli, escavatori, gru, attrezzature. Traccia manutenzioni e utilizzo.',
        position: 'center',
      },
      {
        id: 'nav-risorse',
        title: 'Vai a Risorse',
        description: 'Accedi alla sezione Risorse dal menu Logistica.',
        targetSelector: '[data-tutorial="nav-risorse"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'risorse-list',
        title: 'Elenco Risorse',
        description: 'Vedi tutti i mezzi e attrezzature: tipo, targa/matricola, stato, prossima manutenzione.',
        route: '/risorse',
        position: 'center',
      },
      {
        id: 'filter-tipo',
        title: '🔍 Filtra per Tipo',
        description: 'Filtra per categoria: Veicoli, Escavatori, Gru, Attrezzature Manuali, ecc.',
        targetSelector: '[data-tutorial="filter-risorse"]',
        position: 'bottom',
      },
      {
        id: 'new-risorsa',
        title: '➕ Nuova Risorsa',
        description: 'Clicca "Nuova Risorsa" per aggiungere un mezzo o attrezzatura.',
        targetSelector: '[data-tutorial="btn-new-risorsa"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'form-risorsa',
        title: '📝 Dati Risorsa',
        description: 'Compila: nome, tipo, marca, modello, targa, anno, km attuali, stato.',
        targetSelector: '[data-tutorial="form-risorsa"]',
        position: 'left',
        highlightPadding: 15,
      },
      {
        id: 'manutenzioni',
        title: '🔧 Piano Manutenzioni',
        description: 'Programma le manutenzioni: tagliando, revisione, sostituzione pneumatici. Alert automatici.',
        targetSelector: '[data-tutorial="manutenzioni-risorsa"]',
        position: 'right',
      },
      {
        id: 'prenotazioni',
        title: '📅 Prenotazioni',
        description: 'Prenota i mezzi per i cantieri. Evita conflitti con il calendario prenotazioni.',
        targetSelector: '[data-tutorial="prenotazioni-risorsa"]',
        position: 'right',
      },
      {
        id: 'tracking-km',
        title: '📊 Tracking Km/Ore',
        description: 'Registra km percorsi, ore di utilizzo, rifornimenti carburante per ogni risorsa.',
        targetSelector: '[data-tutorial="tracking-risorsa"]',
        position: 'right',
      },
      {
        id: 'complete',
        title: 'Ottimo! 🎉',
        description: 'Ora gestisci le risorse! Tieni traccia delle manutenzioni per evitare guasti in cantiere.',
        position: 'center',
      },
    ],
  },
  {
    id: 'magazzino-gestione',
    title: 'Gestione Magazzino',
    description: 'Anagrafica articoli, movimenti carico/scarico, alert sottoscorta, inventario',
    icon: 'Boxes',
    estimatedTime: '4 minuti',
    category: 'logistica',
    steps: [
      {
        id: 'intro',
        title: 'Magazzino 📦',
        description: 'Gestisci le scorte: materiali, attrezzature, DPI. Traccia ogni movimento di carico e scarico.',
        position: 'center',
      },
      {
        id: 'nav-magazzino',
        title: 'Vai a Magazzino',
        description: 'Accedi alla sezione Magazzino dal menu Logistica.',
        targetSelector: '[data-tutorial="nav-magazzino"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'magazzino-list',
        title: 'Elenco Articoli',
        description: 'Vedi tutti gli articoli: codice, descrizione, categoria, giacenza, ubicazione.',
        route: '/magazzino',
        position: 'center',
      },
      {
        id: 'alert-sottoscorta',
        title: '⚠️ Alert Sottoscorta',
        description: 'Gli articoli sotto la quantità minima vengono evidenziati in rosso. Riordina subito!',
        targetSelector: '[data-tutorial="alert-sottoscorta"]',
        position: 'top',
      },
      {
        id: 'new-articolo',
        title: '➕ Nuovo Articolo',
        description: 'Clicca "Nuovo Articolo" per aggiungere un prodotto al magazzino.',
        targetSelector: '[data-tutorial="btn-new-articolo"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'form-articolo',
        title: '📝 Dati Articolo',
        description: 'Compila: codice, descrizione, categoria, unità misura, quantità minima, ubicazione.',
        targetSelector: '[data-tutorial="form-articolo"]',
        position: 'left',
        highlightPadding: 15,
      },
      {
        id: 'movimento-carico',
        title: '📥 Carico Magazzino',
        description: 'Registra l\'ingresso merce: DDT fornitore, quantità, data, note.',
        targetSelector: '[data-tutorial="btn-carico"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'movimento-scarico',
        title: '📤 Scarico per Cantiere',
        description: 'Quando prelevi materiale per un cantiere, registra lo scarico indicando la commessa.',
        targetSelector: '[data-tutorial="btn-scarico"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'storico-movimenti',
        title: '📜 Storico Movimenti',
        description: 'Per ogni articolo vedi lo storico completo: chi, quando, quanto, per quale cantiere.',
        targetSelector: '[data-tutorial="storico-movimenti"]',
        position: 'right',
      },
      {
        id: 'inventario',
        title: '📋 Inventario',
        description: 'Genera il report inventario per la verifica fisica delle giacenze.',
        targetSelector: '[data-tutorial="btn-inventario"]',
        position: 'bottom',
        action: 'hover',
      },
      {
        id: 'complete',
        title: 'Perfetto! ✨',
        description: 'Ora gestisci il magazzino! Tieni aggiornate le giacenze per evitare fermi cantiere.',
        position: 'center',
      },
    ],
  },

  // ==================== CATEGORIA: COMPLIANCE ====================
  {
    id: 'gdpr-compliance',
    title: 'GDPR e Privacy',
    description: 'Registro trattamenti, gestione consensi, audit privacy, documentazione',
    icon: 'Lock',
    estimatedTime: '3 minuti',
    category: 'compliance',
    steps: [
      {
        id: 'intro',
        title: 'GDPR Compliance 🔒',
        description: 'Gestisci la privacy aziendale: registro trattamenti, consensi, audit, documentazione GDPR.',
        position: 'center',
      },
      {
        id: 'nav-gdpr',
        title: 'Vai a GDPR',
        description: 'Accedi alla sezione GDPR dal menu Conformità.',
        targetSelector: '[data-tutorial="nav-gdpr"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'gdpr-dashboard',
        title: 'Dashboard GDPR',
        description: 'Panoramica: trattamenti attivi, consensi da rinnovare, audit programmati.',
        route: '/gdpr-compliance',
        position: 'center',
      },
      {
        id: 'registro-trattamenti',
        title: '📋 Registro Trattamenti',
        description: 'Documenta ogni trattamento dati: finalità, base giuridica, categorie dati, periodo conservazione.',
        targetSelector: '[data-tutorial="registro-trattamenti"]',
        position: 'left',
      },
      {
        id: 'consensi',
        title: '✅ Gestione Consensi',
        description: 'Traccia i consensi raccolti da clienti/lavoratori. Monitora scadenze e rinnovi.',
        targetSelector: '[data-tutorial="consensi"]',
        position: 'right',
      },
      {
        id: 'audit',
        title: '🔍 Audit Privacy',
        description: 'Programma e documenta gli audit interni sulla protezione dati.',
        targetSelector: '[data-tutorial="audit-gdpr"]',
        position: 'right',
      },
      {
        id: 'complete',
        title: 'Ottimo! 🎉',
        description: 'Ora gestisci la compliance GDPR! Mantieni aggiornato il registro per essere pronto alle ispezioni.',
        position: 'center',
      },
    ],
  },
  {
    id: 'iso-quality',
    title: 'ISO 9001 - Sistema Qualità',
    description: 'Non conformità, azioni correttive, audit interni, miglioramento continuo',
    icon: 'Award',
    estimatedTime: '3 minuti',
    category: 'compliance',
    steps: [
      {
        id: 'intro',
        title: 'ISO 9001 Qualità 🏆',
        description: 'Gestisci il sistema qualità: registra non conformità, azioni correttive, audit, documenti controllati.',
        position: 'center',
      },
      {
        id: 'nav-iso9001',
        title: 'Vai a ISO 9001',
        description: 'Accedi alla sezione ISO 9001 dal menu Conformità.',
        targetSelector: '[data-tutorial="nav-iso9001"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'iso-dashboard',
        title: 'Dashboard Qualità',
        description: 'Vedi: NC aperte, azioni in corso, prossimi audit, indicatori qualità.',
        route: '/quality-iso',
        position: 'center',
      },
      {
        id: 'non-conformita',
        title: '⚠️ Non Conformità',
        description: 'Registra ogni non conformità rilevata: descrizione, causa, responsabile, data rilevamento.',
        targetSelector: '[data-tutorial="nc-list"]',
        position: 'left',
      },
      {
        id: 'azioni-correttive',
        title: '🔧 Azioni Correttive',
        description: 'Per ogni NC definisci l\'azione correttiva, responsabile, scadenza, verifica efficacia.',
        targetSelector: '[data-tutorial="azioni-correttive"]',
        position: 'right',
      },
      {
        id: 'audit-interni',
        title: '🔍 Audit Interni',
        description: 'Pianifica e documenta gli audit interni. Genera checklist e registra risultati.',
        targetSelector: '[data-tutorial="audit-iso"]',
        position: 'right',
      },
      {
        id: 'complete',
        title: 'Perfetto! ✨',
        description: 'Ora gestisci la qualità ISO 9001! Migliora continuamente i processi aziendali.',
        position: 'center',
      },
    ],
  },
  {
    id: 'iso-environmental',
    title: 'ISO 14001 - Gestione Ambientale',
    description: 'Registro rifiuti, FIR, carbon footprint, checklist ambientali',
    icon: 'Leaf',
    estimatedTime: '3 minuti',
    category: 'compliance',
    steps: [
      {
        id: 'intro',
        title: 'ISO 14001 Ambiente 🌿',
        description: 'Gestisci l\'impatto ambientale: rifiuti, emissioni, consumi energetici, documentazione.',
        position: 'center',
      },
      {
        id: 'nav-iso14001',
        title: 'Vai a ISO 14001',
        description: 'Accedi alla sezione ISO 14001 dal menu Conformità.',
        targetSelector: '[data-tutorial="nav-iso14001"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'env-dashboard',
        title: 'Dashboard Ambientale',
        description: 'Panoramica: rifiuti prodotti, FIR da emettere, carbon footprint, checklist in scadenza.',
        route: '/environmental-iso',
        position: 'center',
      },
      {
        id: 'registro-rifiuti',
        title: '🗑️ Registro Rifiuti',
        description: 'Registra ogni produzione di rifiuti: codice CER, quantità, destinatario, FIR.',
        targetSelector: '[data-tutorial="registro-rifiuti"]',
        position: 'left',
      },
      {
        id: 'fir',
        title: '📄 Formulari (FIR)',
        description: 'Gestisci i Formulari Identificazione Rifiuti: emissione, 4a copia, archivio.',
        targetSelector: '[data-tutorial="fir-list"]',
        position: 'right',
      },
      {
        id: 'carbon-footprint',
        title: '🌍 Carbon Footprint',
        description: 'Calcola le emissioni CO2 aziendali per il reporting di sostenibilità.',
        targetSelector: '[data-tutorial="carbon-footprint"]',
        position: 'right',
      },
      {
        id: 'complete',
        title: 'Ottimo! 🎉',
        description: 'Ora gestisci l\'ambiente ISO 14001! Riduci l\'impatto ambientale dei tuoi cantieri.',
        position: 'center',
      },
    ],
  },
  {
    id: 'dlgs81-safety',
    title: 'D.Lgs 81/08 - Sicurezza Lavoro',
    description: 'DVR, POS, PSC, DUVRI, registro infortuni, modulistica obbligatoria',
    icon: 'Shield',
    estimatedTime: '4 minuti',
    category: 'compliance',
    steps: [
      {
        id: 'intro',
        title: 'D.Lgs 81/2008 📜',
        description: 'La normativa sicurezza lavoro italiana. Gestisci tutta la documentazione obbligatoria in un unico posto.',
        position: 'center',
      },
      {
        id: 'nav-dlgs81',
        title: 'Vai a D.Lgs 81',
        description: 'Accedi alla sezione D.Lgs 81/08 dal menu HSE.',
        targetSelector: '[data-tutorial="nav-dlgs81"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'dlgs-dashboard',
        title: 'Dashboard Sicurezza',
        description: 'Panoramica documenti obbligatori: DVR, POS, PSC, DUVRI, registro infortuni.',
        route: '/safety-dlgs81',
        position: 'center',
      },
      {
        id: 'dvr',
        title: '📋 DVR',
        description: 'Documento Valutazione Rischi aziendale. Carica il DVR e tieni traccia degli aggiornamenti.',
        targetSelector: '[data-tutorial="dvr"]',
        position: 'left',
      },
      {
        id: 'pos',
        title: '📄 POS',
        description: 'Piano Operativo Sicurezza per ogni cantiere. Genera da template o carica esistente.',
        targetSelector: '[data-tutorial="pos"]',
        position: 'right',
      },
      {
        id: 'psc',
        title: '📑 PSC',
        description: 'Piano Sicurezza Coordinamento del CSP. Obbligatorio in cantieri con più imprese.',
        targetSelector: '[data-tutorial="psc"]',
        position: 'right',
      },
      {
        id: 'duvri',
        title: '📝 DUVRI',
        description: 'Documento Unico Valutazione Rischi Interferenziali per lavori in appalto.',
        targetSelector: '[data-tutorial="duvri"]',
        position: 'right',
      },
      {
        id: 'registro-infortuni',
        title: '🏥 Registro Infortuni',
        description: 'Registra ogni infortunio: data, lavoratore, dinamica, giorni assenza, INAIL.',
        targetSelector: '[data-tutorial="registro-infortuni"]',
        position: 'right',
      },
      {
        id: 'moduli',
        title: '📋 Modulistica',
        description: 'Scarica i moduli: verbale riunione periodica, verbale consegna DPI, schede di sicurezza.',
        targetSelector: '[data-tutorial="moduli-dlgs81"]',
        position: 'bottom',
      },
      {
        id: 'complete',
        title: 'Perfetto! ✨',
        description: 'Ora gestisci la sicurezza D.Lgs 81/08! Tutta la documentazione pronta per le ispezioni ASL.',
        position: 'center',
      },
    ],
  },

  // ==================== TUTORIAL AVANZATI ====================
  {
    id: 'impostazioni-personalizzazione',
    title: 'Personalizzazione Interfaccia',
    description: 'Come configurare i moduli visibili nella sidebar e personalizzare l\'esperienza',
    icon: 'Settings',
    estimatedTime: '2 minuti',
    category: 'principale',
    steps: [
      {
        id: 'intro',
        title: 'Personalizza Gest-e ⚙️',
        description: 'Puoi personalizzare quali moduli vedere nella sidebar in base al tuo ruolo e alle tue esigenze.',
        position: 'center',
      },
      {
        id: 'nav-impostazioni',
        title: 'Vai alle Impostazioni',
        description: 'Clicca su Impostazioni nel menu o sull\'icona ingranaggio.',
        targetSelector: '[data-tutorial="nav-impostazioni"]',
        route: '/dashboard',
        position: 'right',
        action: 'click',
        actionDelay: 1500,
      },
      {
        id: 'tab-menu',
        title: '📂 Tab Menu',
        description: 'Seleziona il tab "Menu" per configurare la visibilità dei moduli.',
        route: '/impostazioni',
        targetSelector: '[data-tutorial="tab-menu"]',
        position: 'bottom',
        action: 'click',
        actionDelay: 1000,
      },
      {
        id: 'toggle-moduli',
        title: '✅ Attiva/Disattiva Moduli',
        description: 'Usa gli switch per mostrare o nascondere ogni modulo. I moduli disattivati scompariranno dalla sidebar.',
        targetSelector: '[data-tutorial="toggle-moduli"]',
        position: 'left',
        highlightPadding: 15,
      },
      {
        id: 'reparti',
        title: '🏢 Reparti',
        description: 'Puoi anche disattivare interi reparti (HSE, Commerciale, Amministrazione) se non li utilizzi.',
        targetSelector: '[data-tutorial="toggle-reparti"]',
        position: 'left',
      },
      {
        id: 'complete',
        title: 'Fatto! ✨',
        description: 'Hai personalizzato la tua interfaccia! Vedrai solo i moduli che ti servono.',
        position: 'center',
      },
    ],
  },
  {
    id: 'ricerca-globale',
    title: 'Ricerca Globale Avanzata',
    description: 'Come usare la ricerca per trovare qualsiasi cosa: cantieri, documenti, lavoratori, task',
    icon: 'Search',
    estimatedTime: '2 minuti',
    category: 'principale',
    steps: [
      {
        id: 'intro',
        title: 'Ricerca Globale 🔍',
        description: 'La ricerca globale ti permette di trovare qualsiasi cosa nel sistema in pochi secondi.',
        position: 'center',
      },
      {
        id: 'open-search',
        title: 'Apri la Ricerca',
        description: 'Premi Ctrl+K (⌘+K su Mac) oppure clicca sulla barra di ricerca nella sidebar.',
        targetSelector: '[data-tutorial="global-search"]',
        route: '/dashboard',
        position: 'bottom',
        action: 'click',
        actionDelay: 1000,
      },
      {
        id: 'search-input',
        title: '⌨️ Digita la Query',
        description: 'Inizia a digitare: nome cantiere, lavoratore, codice documento... I risultati appaiono in tempo reale.',
        targetSelector: '[data-tutorial="search-input"]',
        position: 'bottom',
      },
      {
        id: 'categories',
        title: '📂 Categorie Risultati',
        description: 'I risultati sono organizzati per tipo: Cantieri, Lavoratori, Documenti, Task, Imprese.',
        targetSelector: '[data-tutorial="search-categories"]',
        position: 'bottom',
      },
      {
        id: 'navigate',
        title: '➡️ Naviga ai Risultati',
        description: 'Clicca su un risultato per andare direttamente alla pagina corrispondente.',
        targetSelector: '[data-tutorial="search-results"]',
        position: 'bottom',
      },
      {
        id: 'shortcuts',
        title: '⌨️ Shortcut',
        description: 'Usa le frecce ↑↓ per navigare tra i risultati e Enter per aprire. ESC per chiudere.',
        position: 'center',
      },
      {
        id: 'complete',
        title: 'Perfetto! ✨',
        description: 'Ora sai usare la ricerca globale! È il modo più veloce per navigare in Gest-e.',
        position: 'center',
      },
    ],
  },
];

export const getTutorialById = (id: string): Tutorial | undefined => {
  return tutorials.find(t => t.id === id);
};

export const getTutorialsByCategory = (category: Tutorial['category']): Tutorial[] => {
  return tutorials.filter(t => t.category === category);
};

export const getAllCategories = (): Tutorial['category'][] => {
  return ['principale', 'commesse', 'hse', 'commerciale', 'amministrazione', 'logistica', 'compliance'];
};

export const getCategoryLabel = (category: Tutorial['category']): string => {
  const labels: Record<Tutorial['category'], string> = {
    principale: '📊 Dashboard & Navigazione',
    commesse: '🏗️ Gestione Commesse',
    hse: '🛡️ Sicurezza & HSE',
    commerciale: '💼 Ufficio Commerciale',
    amministrazione: '📑 Amministrazione',
    logistica: '🚚 Logistica',
    compliance: '📜 Conformità & Certificazioni',
  };
  return labels[category];
};
